- Documentation/metrics.md
> Fix link to the grafana.json file

- Documentation/README.md
> Documentation: Fix link to DNS troubleshooting tutorial

- pkg/format/format.go
- pkg/format/format_test.go
> pkg/format: Do not show `:0` port

- Documentation/installation.md
> doc: Add a step to clone hubble repo before running helm

- pkg/parser/threefour/parser.go
> parser: Log a warning if GetIdentity() fails

- README.md
Should help people find support with Slack
Signed-off-by: Sergey Generalov <sergey@isovalent.com>
> Add Get in touch section to main readme

- pkg/printer/printer.go
> pkg/printer: Use interface in print methods

- install/kubernetes/hubble/templates/deployment.yaml
- install/kubernetes/hubble/values.yaml
Signed-off-by: Dan Sexton <dan.b.sexton@gmail.com>
> Created value for hubble-ui replicas

- install/kubernetes/hubble/templates/ingress.yaml
- install/kubernetes/hubble/values.yaml
Signed-off-by: Dan Sexton <dan.b.sexton@gmail.com>
> Added hubble-ui ingress to Helm chart

- install/kubernetes/hubble/values.yaml
- tutorials/deploy-hubble-servicemap/hubble-all-minikube.yaml
Signed-off-by: Dmitry Kharitonov <geakstr@me.com>
> hubble-ui: changed docker image repo to cilium/hubble-ui

- pkg/container/ring.go
- pkg/container/ring_reader.go
- pkg/container/ring_reader_test.go
- pkg/container/ring_test.go
- pkg/server/local_observer.go
- pkg/server/observer.go
- pkg/server/observer_test.go
This PR introduces `RingReader` and refactors the get flows logic.
Fixes #10, Fixes #68
> server: refactor getflows

- pkg/api/v1/endpoint.go
- pkg/api/v1/endpoint_test.go
Also add .idea directory to gitignore.
> endpoint: Add a function to lookup by container ID

- pkg/cilium/state.go
> cilium: Add getters for Cilium client and state caches

- Dockerfile
- cmd/serve/serve.go
See commits messages.
Updates #91
> enable gops by default

- install/kubernetes/hubble/Chart.yaml
- install/kubernetes/hubble/templates/daemonset.yaml
- install/kubernetes/hubble/templates/deployment.yaml
- install/kubernetes/hubble/values.yaml
This PR adds the ability to set (in the case of the Hubble UI) and override (in the case of Hubble itself) the priority class being used, as well as the ability to set resource requests and limits.
> Allow for setting the priority class and resource requests/limits.

- pkg/printer/printer.go
- pkg/printer/printer_test.go
> printer: Pass right parameters to Hostname() function

- README.md
I was reading the readme, found this simple typo.
I don't think any explanation's necessary :)
> Fix trivial typo on README

- cmd/root.go
Add zsh as an option for hubble command completion. The default behavior
of the `completition` command is still bash completition, i.e. if no
argument or `bash` is specified.
The same was added to the `cilium` command in cilium/cilium#9882
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
> cmd: add completion option for zsh

- pkg/api/v1/endpoint_test.go
- pkg/cilium/ipcache_test.go
Details in individual commit messages.
> Fix go vet reports

- .github/workflows/unittests.yml
- Makefile
- make: add check target
- actions: use `make check` for static checks, add separate step for tests
> add make check target; separate step for tests

- cmd/serve/serve.go
- pkg/server/local_observer.go
- pkg/server/local_observer_test.go
- pkg/server/observer.go
- pkg/server/observer_test.go
- pkg/server/serveroption/option.go
Two individual commits. One adds the pattern for options, the other implements the numerical options for the ring size and monitor buffer.
> pkg/server: Option

- cmd/serve/serve.go
The 'duration' option allowed shutting down the server after the given duration.
This option was apparently added to make integration tests easier. With hubble now being embedded into Cilium, it does not make a whole lot of sense to keep it. It's also unlikely that it was being used at all.
> cmd/serve: remove duration option

- pkg/api/v1/endpoint.go
- pkg/api/v1/endpoint_test.go
- pkg/api/v1/types.go
- pkg/cilium/endpoint_test.go
- pkg/parser/endpoint/endpoint.go
- pkg/parser/endpoint/endpoint_test.go
This field is not being used, thus remove it.
> api/endpoint: remove Created field from endpoint struct

- Makefile
This PR will fail until #82 is fixed.
> reduce timeout for tests and make it configurable; run tests with -race flag

- pkg/server/local_observer.go
The ring ringer spawns goroutines when serving a `follow` request.
These goroutines must terminate when the request is done, otherwise
the goroutines are leaked. Therefore this commit introduces a
per-request context for the `GetFlows` gRPC call which is cancelled
when the request is completed, allowing consumers of the context to
terminate as well.
Fixes: #215
> server: Introduce per-request context

- .github/workflows/unittests.yml
> actions: Trigger on release branches

- cmd/root.go
For consistency with how cilium does root cmd.
> cmd: Export RootCmd

- Documentation/README.md
- Documentation/quickstart.md
- README.md
> doc: Add a Quickstart section to the documentation

- Documentation/quickstart.md
Ref: https://github.com/cilium/cilium/pull/11124
> helm: Update hubble cli options

- cmd/config.go
- cmd/root.go
Started the process in the previous commit, but forgot to
actually move all the relevant code over.
> cmd: Finish config move

- Dockerfile
- Makefile
> adjust dockerfile and makefile for "serve" command removal

- Documentation/installation.md
Cilium 1.6 support is not complete, discourage use of it.
> Require Cilium 1.7.x

- .github/workflows/unittests.yml
- Dockerfile
> v0.5 backports 2020-07-22

- .github/cilium-actions.yml
- commit sign-off check
- release note label
> Add little helper actions

- README.md
> Readme: remove old beta warning and make a components table

- .github/workflows/unittests.yml
- Dockerfile
- Makefile
- #336 -- update Go version to v1.14.7 (@Rolinh)
> v0.6: backports 2020-08-10

- .github/workflows/unittests.yml
- Dockerfile
- #336 -- update Go version to v1.14.7 (@Rolinh)
> v0.5: backports 2020-08-10

- tutorials/README.md
Add missing dot and a new line at the end.
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>
> tutorials: Fix README.md

- .github/workflows/unittests.yml
- Dockerfile
- Makefile
> Update Go to v1.15, drop support for darwin/386, add support for linux/[arm,arm64]

- contrib/scripts/check-fmt.sh
https://github.com/koalaman/shellcheck/wiki/SC2038
> Fixes SC2038 in check-fmt.sh

- cmd/root.go
The configuration file location is now platform dependent.
> cmd: fix help message for the `-config` flag

- cmd/config/set.go
Address an issue where values other than the one specified using `config
set KEY ...` were set to their default value in the configuration file.
Key/value pairs provided via environment variables and/or flags were
also written to the file, which was an unwanted side-effect of the
previous implementation.
With this rewrite, only values that are explicitly set via the `config
set` subcommand are written to the configuration file. Key/value pairs
that were already in the configuration file, if any, are preserved.
> cmd/config: only write provided key/value when using set subcommand

- cmd/observe/observe.go
- cmd/status/status.go
> cmd: update observe and status command description/formatting

- RELEASE.md
See commits for the rationale.
> update release instructions

- cmd/observe/observe.go
- cmd/observe/observe_usage.go
> cmd/observe: add all flags

- cmd/observe/observe.go
Some of the flags possible values are known. This is valid for flags:
- type
- verdict
- http-status
- http-method
- output
Example:
hubble observe --type <TAB>
agent           capture         debug           drop            l7              policy-verdict  trace
Adding completion support for other flags would require dynamic
completion and, in most cases, access to the kubernetes cluster (to
complete things like namespace, pod, service, etc) which makes it much
harder to implement.
> cmd/observe: add shell completion support for various flags

- cmd/common/config/flags.go
- cmd/common/conn/tls.go
- cmd/common/validate/tls.go
- cmd/config/set.go
- cmd/node/list.go
- cmd/observe/observe.go
- cmd/peer/watch.go
- cmd/reflect/reflect.go
- cmd/status/status.go
This commit does not contain any functional changes.
> cmd: use config key constants instead of hardcoded strings

- Dockerfile
- Makefile
> Bump alpine base image to 3.13

- go.mod
- go.sum
- vendor/honnef.co/go/tools/go/ir/exits.go
- vendor/honnef.co/go/tools/lintcmd/version/version.go
- vendor/honnef.co/go/tools/pattern/match.go
- vendor/honnef.co/go/tools/staticcheck/lint.go
- vendor/honnef.co/go/tools/stylecheck/lint.go
- vendor/modules.txt
> vendor: bump honnef.co/go/tools from v0.1.1 to v0.1.2

- README.md
Fix the link to Metrics Documentation on README
Signed-off-by: Kaito Ii <kaitoii1111@gmail.com>
> Fix brokenlink on README.md

- cmd/node/list.go
- cmd/node/list_test.go
This PR aims to achieve the following:
Signed-off-by: Simarpreet Singh <simar@linux.com>
> cmd/node: Refactor & Test output methods

- cmd/observe/observe.go
The function `signal.NotifyContext` is new in Go v1.16. Replacing our
own implementation to cancel the command context when SIGINT is
received allows shoving some lines of code.
> cmd/observe: use signal.NotifyContext to cancel context on SIGINT

- go.mod
- go.sum
- vendor/google.golang.org/grpc/balancer_conn_wrappers.go
- vendor/google.golang.org/grpc/clientconn.go
- vendor/google.golang.org/grpc/version.go
- vendor/honnef.co/go/tools/analysis/report/report.go
- vendor/honnef.co/go/tools/go/ir/dom.go
- vendor/honnef.co/go/tools/go/ir/lift.go
- vendor/honnef.co/go/tools/lintcmd/version/version.go
- vendor/honnef.co/go/tools/simple/lint.go
- vendor/honnef.co/go/tools/staticcheck/lint.go
- vendor/modules.txt
These are bugfix releases that fix potential crashes.
> vendor: bump grpc to v1.37.1; honnef tools to v0.1.4

- go.mod
- go.sum
- vendor/google.golang.org/grpc/balancer_conn_wrappers.go
- vendor/google.golang.org/grpc/clientconn.go
- vendor/google.golang.org/grpc/version.go
- vendor/honnef.co/go/tools/analysis/report/report.go
- vendor/honnef.co/go/tools/go/ir/dom.go
- vendor/honnef.co/go/tools/go/ir/lift.go
- vendor/honnef.co/go/tools/lintcmd/version/version.go
- vendor/honnef.co/go/tools/simple/lint.go
- vendor/honnef.co/go/tools/staticcheck/lint.go
- vendor/modules.txt
Backport #552 to the v0.8 branch.
> v0.8: vendor: bump grpc to v1.37.1; honnef tools to v0.1.4

- Makefile
- go.mod
- go.sum
- vendor/github.com/cilium/cilium/AUTHORS
- vendor/github.com/cilium/cilium/pkg/defaults/defaults.go
- vendor/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/const.go
- vendor/github.com/google/go-cmp/cmp/path.go
- vendor/github.com/google/go-cmp/cmp/report_slices.go
- vendor/modules.txt
Update Cilium to v1.10.3 and backport #589.
> v0.8: update cilium to v1.10.3, backport git version fix

- cmd/observe/flows.go
> Log a debug message when reading from stdin

- CHANGELOG.md
- RELEASE.md
> release and changelog misc improvements

- .golangci.yml
- go.mod
- go.sum
- vendor/gopkg.in/yaml.v3/parserc.go
- vendor/modules.txt
See https://github.com/go-yaml/yaml/issues/665.
> vendor: update yaml.v3 to v3.0.1

- CHANGELOG.md
_v0.10 backport of https://github.com/cilium/hubble/pull/753_
> [v0.10] CHANGELOG.md: fix PR ref in the v0.10.0 release note

- pkg/printer/printer.go
- pkg/printer/printer_test.go
> compact: Include DNS observation source

- .github/dependabot.yml
See commits, I would also be inclined to bump the `open-pull-requests-limit` (e.g. to 5) and maybe the schedule interval to daily.
> dependabot config improvements

- cmd/observe/agent_events.go
- cmd/observe/debug_events.go
- cmd/observe/flows.go
- cmd/observe/flows_filter_test.go
- cmd/observe/observe.go
Reverts cilium/hubble#851
This broke using some flags, so revert until we can fix the regression.
> Revert "Add hubble observe flows"

- .github/workflows/tests.yml
- .golangci.yml
- Makefile
- cmd/cli_test.go
- cmd/observe/agent_events_test.go
- cmd/observe/debug_events_test.go
- cmd/observe/flows.go
- cmd/observe/flows_test.go
- cmd/observe/io_reader_observer.go
- cmd/observe/io_reader_observer_test.go
- cmd/status/status.go
- go.mod
- pkg/printer/printer.go
- pkg/printer/printer_test.go
> update Go to v1.20.2, golangci-lint to v1.52.2

- cmd/observe/flows.go
- cmd/record/record.go
- pkg/printer/printer.go
- pkg/printer/printer_test.go
Pulling @gandro for the recorder part.
> SCTP support

- .github/workflows/build-images-release.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/integration-tests.yaml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- Makefile
Turns out the tags had `v` prefixes that I missed and I didn't notice the dependency dashboard in my fork telling me it had errors.
I've properly tested this in my fork. See my dependency dashboard: https://github.com/chancez/hubble/issues/8 has no errors and my PR here is the same as my master branch of the fork https://github.com/chancez/hubble/commits/master
> Fix Renovate datasources

- .github/renovate.json5
See https://github.com/cilium/hubble/pull/1036#issuecomment-1549605905
Closes #1036
> Renovate: Ignore pflag

- .github/renovate.json5
This might fix https://github.com/cilium/hubble/pull/1081
> Add golang to matchPackageNames for go deps groups

- cmd/observe/flows_filter.go
- cmd/observe/flows_filter_test.go
Backport of https://github.com/cilium/hubble/pull/1109
> [v0.11] fix workload and identity filters

- .github/renovate.json5
- .github/workflows/codeql-analysis.yml
- .github/workflows/integration-tests.yaml
- .github/workflows/tests.yml
- CODE_OF_CONDUCT.md
- README.md
- RELEASE.md
> switch the default git branch from master to main

- .github/workflows/build-images-release.yaml
> v0.12: ci: build image for arm64

- .github/workflows/codeql-analysis.yml
- .github/workflows/integration-tests.yaml
- .github/workflows/tests.yml
- go.mod
Use go.mod for version for setup-go GHA
> Switch to using go.mod for version in setup-go GHA

- CHANGELOG.md
They were all released this year
> CHANGELOG: Use correct year for the last few releases

- CHANGELOG.md
documenting the new release process here at the same time => https://github.com/cilium/hubble/pull/1479
> Prepare for release v1.16.0-pre.2

- .github/ISSUE_TEMPLATE/release.md
GitHub complains about the missing about field.
> Fix the release issue template

- README.md
- RELEASE.md
Fixes: https://github.com/cilium/cilium/issues/34043
Related pull requests:
https://github.com/cilium/cilium.io/pull/524
https://github.com/cilium/cilium/pull/34044
> doc: update slack channel reference

- .github/renovate.json5
Note: we had two "schedule" sections. Let's keep the one that runs on Tuesdays rather than the one that runs on Fridays.
Ref: #1651
> migrate Renovate config
