install/kubernetes/README.md, install/kubernetes/hubble/templates/daemonset.yaml, install/kubernetes/hubble/values.yaml
This switches the Helm chart over to use the image of the open-source repository of Hubble. Deployments of the preview of Hubble-UI still use the old image.
=> install/kubernetes: Switch to quay.io/cilium/hubble

Documentation/installation.md
When installing Cilium v1.7.0-rc1, the image tag has to be set via Helm.
=> docs: Set Cilium image tag when installing via Helm

pkg/ipcache/ipcache.go, pkg/ipcache/ipcache_test.go, pkg/parser/getters/getters.go, pkg/parser/new.go, pkg/parser/seven/parser.go, pkg/parser/seven/parser_test.go, pkg/parser/threefour/parser.go, pkg/parser/threefour/parser_test.go, pkg/server/ipcache.go, pkg/server/ipcache_test.go, pkg/server/observer_test.go, pkg/testutils/fake.go
Previously, the IPCache was only consulted to obtain the K8s pod name
and namespace. However, we also want to obtain the numeric security
identity to fetch labels for endpoints running on remote nodes. This
change extends the IPCache interface to expose this information to the
parser.
Flow endpoints running on local nodes still be populated from the local
endpoint collection, as this will us save us an extra api call to obtain
the labels. Additionally, for local endpoints we also will populate the
endpoint id this way (which is distinct from the numerical security
identity and currently unavailable for remote endpoints).
Fixes: #8
=> parser: Populate labels for remote endpoints

install/kubernetes/hubble/templates/daemonset.yaml, install/kubernetes/hubble/values.yaml, tutorials/deploy-hubble-servicemap/hubble-all-minikube.yaml
Adds "0.0.0.0:50051" to `listenClientUrls` when `ui.enabled` is true.
This ensures that Hubble exposes its gRPC service via TCP, which is
required for the UI.
In addition, this PR also cleans up the Helm chart with regards to the
UI. The new hubble-all-minikube.yaml has been gerated with the following
command:
helm template hubble \
--namespace kube-system \
--set metrics.enabled="{dns:query,drop,tcp,flow,port-distribution}" \
--set ui.enabled=true \
> ../../tutorials/deploy-hubble-servicemap/hubble-all-minikube.yaml
Might fix issue #15.
=> helm: Enable TCP ports when ui.enable=true

install/kubernetes/hubble/templates/deployment.yaml
Hubble-UI helm template uses hardcoded "kube-system" namespace.
=> Fixed UI deployment to use user specified namespace to call hubble-grpc

cmd/server.go, pkg/api/v1/endpoint.go, pkg/api/v1/endpoint_test.go, pkg/server/endpoint.go, pkg/server/endpoint_test.go, pkg/server/observer.go
Endpoint labels are not always available when an endpoint is initially created. The following `cilium monitor` output exemplifies this:
>> Endpoint created: {"id":1407,"pod-name":"deathstar-657477f57d-5nl8t","namespace":"default"}
>> IPCache entry upserted: {"cidr":"10.16.65.104/32","id":20927,"host-ip":"192.168.33.11","encrypt-key":0,"namespace":"default","pod-name":"deathstar-657477f57d-5nl8t"}
>> IPCache entry upserted: {"cidr":"f00d::a10:0:0:dc8e/128","id":20927,"host-ip":"192.168.33.11","encrypt-key":0,"namespace":"default","pod-name":"deathstar-657477f57d-5nl8t"}
>> Endpoint regenerated: {"id":1407,"labels":["k8s:io.cilium.k8s.policy.serviceaccount=default","k8s:io.cilium.k8s.policy.cluster=default","k8s:class=deathstar","k8s:org=empire","k8s:io.kubernetes.pod.namespace=default"]} …
=> Fix missing labels in new local endpoints

.github/workflows/unittests.yml
Master is not compatible with v1. We can migrate to v2 once it's out
of beta.
=> actions: Nail the version of actions/checkout to v1

pkg/api/v1/endpoint.go, pkg/api/v1/endpoint_test.go, pkg/server/endpoint.go, pkg/server/endpoint_test.go, pkg/server/observer.go
This adds two commits improving the handling of deleted endpoints.
The first commit ensures that no deleted endpoints are used to annotate flows, while the second periodically removes deleted endpoints from the cache.
=> endpoints: Improve handling of deleted endpoints

pkg/api/v1/flow.go, pkg/api/v1/interface.go, pkg/api/v1/types.go, pkg/container/ring.go, pkg/container/ring_test.go, pkg/filters/filters.go, pkg/filters/filters_test.go, pkg/metrics/api/api.go, pkg/metrics/api/context.go, pkg/metrics/api/registry_test.go, pkg/metrics/dns/handler.go, pkg/metrics/drop/handler.go, pkg/metrics/flow/handler.go, pkg/metrics/http/handler.go, pkg/metrics/icmp/handler.go, pkg/metrics/metrics.go, pkg/metrics/port-distribution/handler.go, pkg/metrics/tcp/handler.go, pkg/server/observer.go, pkg/server/observer_test.go
This introduces an interface for `pb.Flow` and generalizes `v1.Event` to return an instance of the interface. This allows better mocking and alternative flow implementations in the future.
The second PR moves the `metrics.ProcessFlow` over to the new interface .
=>  api: Introduce interface for pb.Flow 

Makefile, pkg/parser/threefour/parser_test.go
This PR:
- adds the `ineffassign` target, similar to what we have in Cilium
- fixes one ineffassign error
=> make: Add ineffassign target

cmd/observe.go, cmd/status.go
Allow the $HUBBLE_SOCK environment variable to override the server socket
path for the client.
=> Add support for specifying server in client via env variable

.github/workflows/unittests.yml, Makefile
- Check whether binaries of linters exist
- Add `check-fmt` and `ineffassign` targets to the `lint` target
=> make: Follow up changes

install/kubernetes/helpers.bash, tutorials/explore-flow-queries/README.md
Defines a set of helpers to simplify usage of Hubble with Kubernetes.
Signed-off-by: Thomas Graf <thomas@cilium.io>
=> Documentation: Provide Kubernetes bash helpers

cmd/observe.go, cmd/observe/observe.go, cmd/observe/observe_filter.go, cmd/observe/observe_filter_test.go, cmd/observe/observe_usage.go, cmd/observe/observe_usage_test.go, cmd/root.go, cmd/serve/serve.go, cmd/status/status.go, pkg/api/const.go
This isolates individual sub-commands from each other and should set up a better structure moving forward. `pacakge cmd` was getting a little out of hand.
There is still more work that can be done to make these packages better testable (mostly removing a lot of the global vars and stuff), but it's currently not a priority.
=> Split up cmd package

install/kubernetes/hubble/templates/daemonset.yaml, install/kubernetes/hubble/templates/servicemonitor.yaml, install/kubernetes/hubble/templates/svc.yaml, install/kubernetes/hubble/values.yaml
This adds an option to create prometheus-operator [ServiceMonitor](https://github.com/coreos/prometheus-operator/blob/master/Documentation/design.md#servicemonitor) resource.
=> Added prometheus-operator ServiceMonitor

install/kubernetes/hubble/templates/daemonset.yaml, tutorials/deploy-hubble-servicemap/hubble-all-minikube.yaml
The annnotation `scheduler.alpha.kubernetes.io/critical-pod` is now obsolete and has to be replaced by the priorityClassName spec instead to mark an add-on pod as critical.
There exists 2 priority classes to mark an add-on pod as critical (only under the `kube-system` namespace), namely:
- `system-cluster-critical` (value: 2000000000)
- `system-node-critical`    (value: 2000001000)
As the hubble pod is critical to the node itself, the system-node-critical priority class is appropriate for hubble pods.
Closes #25
=> helm: set priorityClassName to system-node-critical for hubble pods

pkg/parser/threefour/parser_test.go, pkg/testutils/fake.go
=> refactor: Move FakeIdentityGetter to testutils

Makefile
Define the TARGET variable that is used both by the `hubble` and `clean` targets.
=> make: fix clean target

cmd/serve/serve.go, pkg/server/endpoint_test.go, pkg/server/ipcache.go, pkg/server/ipcache_test.go, pkg/server/observer.go
To be consistent with other channels like endpointEvents and logRecord.
=> refactor: Move ipCacheEvents channel inside ObserverServer

cmd/serve/serve.go, pkg/server/endpoint_test.go, pkg/server/ipcache.go, pkg/server/ipcache_test.go, pkg/server/observer.go
This reverts commit d02b338a9eb5e60268466780a83f434002b0a603.
=> Revert "refactor: Move ipCacheEvents channel inside ObserverServer"

cmd/serve/serve.go, pkg/cilium/client/client.go, pkg/format/format.go, pkg/format/format_test.go, pkg/parser/getters/getters.go, pkg/parser/new.go, pkg/parser/seven/parser.go, pkg/parser/seven/parser_test.go, pkg/parser/threefour/parser.go, pkg/parser/threefour/parser_test.go, pkg/printer/printer.go, pkg/printer/printer_test.go, pkg/server/endpoint_test.go, pkg/server/observer.go, pkg/server/observer_test.go, pkg/server/service.go, pkg/server/service_test.go, pkg/servicecache/service_cache.go, pkg/servicecache/service_cache_test.go, pkg/testutils/fake.go
This turns the output of `hubble observe` from this:
```
Jan 22 13:25:22.808 []: default/alpine:55822 -> 172.20.0.113:80(http) from-endpoint FORWARDED (TCP Flags: SYN)
```
To this (when ip translation is enabled):
```
Jan 22 13:25:22.808 []: default/alpine:55822 -> default/deathstar:80(http) from-endpoint FORWARDED (TCP Flags: SYN)
```
In short, the service IP is replaced by `<namespace>/<service name>`. The service port is left as it can be a useful information for whoever is observing the flow.
Note that for this feature to work, Cilium 1.7+ must be used. With Cilium <= 1.6, service addresses are simply not translated.
Closes #48
=> enable service address to service name translation

cmd/observe/observe.go, pkg/printer/options.go, pkg/printer/printer.go, pkg/printer/printer_test.go
- Rename Set{IP,Port}Translation to With{IP,Port}Translation to be
consistent with other options.
- Export GetPorts/GetHostNames/GetFlowType so that they can be called
from outside the printer package.
=> pkg/printer: Clean up the printer package

cmd/serve/serve.go, pkg/server/dns_test.go, pkg/server/endpoint_test.go, pkg/server/local_observer.go, pkg/server/local_observer_test.go, pkg/server/observer.go
Define an interface for the observer server, and add a new implementation
LocalObserverServer. It ignores all the state change events and does not
connect to Cilium's monitor socket. It's meant to be started embeeded in
Cilium process so that:
1. the parser can access Cilium state directly without making a copy, and
2. the server can receive monitor payloads by registering a listener.
The observer server interface adds a new method HandleMonitorSocket() that
encapsulates the logic for connecting to the monitor socket and handling
monitor events instead of exposing the logic in cmd/serve.go.
=> serve: Add a "local" server

cmd/serve/serve.go, pkg/server/dns_test.go, pkg/server/endpoint_test.go, pkg/server/ipcache_test.go, pkg/server/local_observer.go, pkg/server/observer.go, pkg/server/observer_test.go, pkg/server/service_test.go
Use LocalObserverServer in ObserverServer instead of duplicating the
same code, and move the gRPC server code to LocalObserverServer. Define
an interface GRPCServer so that we can use different implementation for
unit tests etc..
With this change, there is a clear split between LocalObserverServer
and ObserverServer. LocalObserverServer is responsible for maintaining
the ring buffer and implementing gRPC API, while ObserverServer is
responsible for consuming monitor events and syncing Cilium state.
=> server: Refactor LocalObserverServer and ObserverServer

pkg/fqdncache/fqdncache.go
(*endpoint).insertDNSLookup already checks for the passed entry being
nil, so the nil check before the call can be omitted.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
=> fqdncache: remove unnecessary nil check

Dockerfile
This gets rid of the error:
build flag -mod=vendor only valid when using modules
Closes #79
=> Dockerfile: Use golang:1.13.7

pkg/api/v1/endpoint.go, pkg/server/endpoint_test.go, pkg/server/observer.go
Move the endpointsHandler interface definition to pkg/api/v1/entpoints.go.
It seems like a natual place to define the interface since this is where
the Endpoint struct implements all the interface methods.
This patch also adds GetEndpointByContainerID method to the interface.
=> refactor: Move endpointsHandler to pkg/api/v1/entpoints.go

pkg/server/endpoint_test.go, pkg/server/ipcache_test.go, pkg/server/service_test.go, pkg/testutils/fake.go
Move fake{CiliumClient,EndpointsHandler} to fake.go to be consistent
with other fake implementations.
=> refactor: Move fake{CiliumClient,EndpointsHandler} to testutils

cmd/serve/serve.go, pkg/cilium/client/client.go, pkg/cilium/dns.go, pkg/cilium/dns_test.go, pkg/cilium/endpoint.go, pkg/cilium/endpoint_test.go, pkg/cilium/ipcache.go, pkg/cilium/ipcache_test.go, pkg/cilium/service.go, pkg/cilium/service_test.go, pkg/cilium/state.go, pkg/server/observer.go, pkg/server/observer_test.go
Following up on https://github.com/cilium/hubble/pull/69, introduce
cilium.State struct that encapsulates caches and channels for managing
Cilium state. After this refactoring, there are 3 components to hubble
server:
- CiliumState: Maintains various states from Cilium.
- GRPCServer: Keeps recent flows in a buffer and exposes a gRPC endpoint
for serving flows.
- ObserverServer: Connects to Cilium's monitor socket and sends monitor
events to GRPCServer and CiliumState.
=> refactor: Move Cilium state caches to cilium package

pkg/api/v1/endpoint.go, pkg/api/v1/endpoint_test.go, pkg/testutils/fake.go
Similar to 2d3e85e, but this function looks up cilium endpoint by
pod name instead of container ID.
=> endpoint: Add a function to lookup by pod name

cmd/serve/serve.go
Hubble server typically runs inside a container, so this message is
not very useful.
=> serve: Remove printf

install/kubernetes/hubble/Chart.yaml, install/kubernetes/hubble/templates/daemonset.yaml
In #105 I had accidentally misplaced the `resources` field for the Hubble daemonset (apologies for that). This PR fixes that issue.
=> Fix misplaced 'resources' field.

api/v1/Makefile
GNU make v4.3 breaks our trailing space hack. This commit inserts the trailing space
in the api/v1/Makefile by introducing a `$space` variable containing a
single space.
Without this fix, generating the gRPC API fails with the following
error:
```console
$ make -C api/v1
[...]
google,Mprotobuf,Mduration.proto=github.com,Mgogo,Mprotobuf,Mtypes,M: No such file or directory
make: *** [Makefile:32: flow/flow.pb.go] Error 1
```
See also https://github.com/cilium/cilium/pull/10173
=> api: Fix broken trailing space in make v4.3

cmd/serve/serve.go, pkg/cilium/state.go, pkg/logger/log.go, pkg/server/local_observer.go, pkg/server/observer.go
Cilium uses logrus field to specify subsystems like this:
https://github.com/cilium/cilium/blob/b6f2e75d5b98bc200817da41f96c6522866cdd4a/daemon/daemon_main.go#L89
This PR modifies observer server and serve command to accept Entry
instead of Logger so that Cilium can configure the subsystem field
for Hubble.
Ref #97
=> logging: Use logrus.Entry

cmd/serve/serve.go
- Export EnableMetrics so that Cilium can use it.
- Take metricsServer as an argument.
=> serve: Export EnableMetrics function

Documentation/installation.md
Remove the Helm dependency in the installation guide to reduce the
friction while getting started with Cilium/Hubble.
Closes #101
=> doc: Use generated YAML files in Installaton Guide

pkg/metrics/flow/handler.go, pkg/metrics/flow/handler_test.go, pkg/metrics/flow/plugin.go, pkg/testutils/fake.go
Flow plugins doesn't expose source and destination prometheus
labels. This patch will add support for the context options to support
additional prometheus labels.
Signed-off-by: Arthur Evstifeev <aevstifeev@gitlab.com>
=> Add options to the flow metrics

install/kubernetes/hubble/templates/daemonset.yaml, install/kubernetes/hubble/values.yaml, pkg/api/const.go, pkg/api/socket.go, pkg/api/socket_test.go
Set HUBBLE_GROUP_NAME environment variable to override the group name.
Closes #122
=> socket: Make the unix domain socket group configurable

cmd/observe/observe.go, cmd/status/status.go, install/kubernetes/hubble/templates/daemonset.yaml, install/kubernetes/hubble/values.yaml, pkg/api/const.go, pkg/api/socket.go, pkg/api/socket_test.go
Set HUBBLE_DEFAULT_SOCKET_PATH environment variable to override the
default server for status and observe commands.
Closes #124
=> socket: Make the default server for status/observe configurable

cmd/observe/observe.go, pkg/printer/options.go
This makes it more easy to find out about all available out formatting options. Furthermore, when old formatting flags will be removed, providing flags that are incompatible, such as `--json --compact`, will not be possible anymore. For now however, just deprecate the old formatting flags in order to not to break compatibility.
This also fixes a bug where `--follow --dict` was incorrectly defaulting to the compact output.
Fixes #121
=> cmd/observe: deprecate --compact, --dict, --json flags, add --output

pkg/parser/seven/parser.go, pkg/parser/seven/parser_test.go
DNSGetter.GetNamesOf looks up DNS names of an IP address from the FQDN
cache of a given endpoint, so we need to pass:
- (source endpoint ID, destination IP) for destination names
- (destination endpoint ID, source IP) for source names
Unit test was passing because the fake implementation of DNSGetter
implemented GetNamesOf incorrectly.
I also tested the CLI manually. Before the fix:
default/tiefighter:52768 -> 72.30.35.9:80(http) http-request FORWARDED (HTTP/1.1 GET http://yahoo.com/)
72.30.35.9:80(http) -> default/tiefighter:52768 http-response FORWARDED (HTTP/1.1 301 196ms (GET http://yahoo.com/))
After the fix:
default/tiefighter:44530 -> yahoo.com:80(http) http-request FORWARDED (HTTP/1.1 GET http://yahoo.com/)
yahoo.com:80(http) -> default/tiefighter:44530 http-response FORWARDED …
=> parser: Fix parameters to DNSGetter.GetNamesOf

pkg/container/ring_reader.go, pkg/container/ring_reader_test.go
By contract, RingReader should only return <nil> when no event can be read. In the case of NextFollow(), one should block until an event is read or the context is cancelled.
However, it appears that under certain circumstances, typically when the ring buffer is empty, <nil> events may be sent to the channel by Ring.readFrom(). In such a case, one should ignore the <nil> event and keep reading/waiting until a non-nil event is being sent to the channel or the context is cancelled.
Fixes #134 
/cc @michi-covalent Can you please confirm that if fixes the issue you reported?
=> container/ring_reader: never return nil events on NextFollow()

pkg/container/ring.go
Make sure to atomic load `r.write` and get rid of `r.full` altogether as it was only used in `Len()` and not stricly necessary.
This fixes a data race on `r.full` as it wasn't atomically updated.
Fixes #140
=> container/ring: fix data race on r.full

.github/workflows/unittests.yml, Dockerfile, go.mod, vendor/modules.txt
Note that `go mod vendor` had to be re-run to sync `vendor/modules.txt` as Go v1.14 reported inconsistent vendoring (missing `explicit` and `replaced` directives in `vendor/modules.txt`).
/cc @michi-covalent
=> update Go to v1.14.0

vendor/modules.txt
Essentially, this means running `go mod vendor` with Go 1.14 (I should have re-sync #146 before merging). This fixes the current test failure on master.
=> vendor: mark goleak as explicit

pkg/api/v1/endpoint.go, pkg/api/v1/interface.go, pkg/api/v1/types.go, pkg/cilium/ipcache.go, pkg/cilium/ipcache_test.go, pkg/parser/getters/getters.go, pkg/parser/threefour/parser.go, pkg/parser/threefour/parser_test.go, pkg/testutils/fake.go
This allows the embedded mode to use a different underlying endpoint
structure without having to convert to v1.Endpoint.
Ref #150
=> endpoint: Define an interface to access endpoint fields

main.go
Every Go release brings its set of new features and other changes. When using these new features, the appropriate Go version should be used.
In some cases, using newly introduced features simply means that the code will no longer compile on older versions of Go. This would be the case if one starts using error wrapping introduced in Go 1.13 and trying to compile the code with an older version of Go for instance.
However, it is also possible that a new functionality change still compiles fine with an older version of Go, thus possibly introducing subtle bugs if the software is compiled with an older version of Go.
Transparent monotonic clock support introduced in Go 1.9 would fall into this category for example.
In summary, it is hard to guarantee support for multiple versions of Go …
=> ensure building fails on unsupported versions of Go

Makefile
From the [Go 1.14 release notes](https://golang.org/doc/go1.14):
> When the main module contains a top-level vendor directory and its go.mod file specifies go 1.14 or higher, the go command now defaults to -mod=vendor for operations that accept that flag
Since the go.mod file now specifies go 1.14, it is no longer necessary to manually add the `-mod=vendor` flag to go commands.
=> make: remove -mod=vendor from go commands

pkg/container/ring.go, pkg/container/ring_test.go
The ring actually handles the generic object of type `v1.Event` rather than flows. This commits brings no functional changes.
=> container/ring: replace references to 'flow' by 'event'

pkg/api/v1/interface.go, pkg/api/v1/types.go, pkg/parser/endpoint/endpoint.go, pkg/parser/endpoint/endpoint_test.go, pkg/parser/threefour/parser.go, pkg/parser/threefour/parser_test.go
This adds the numerical security identity to `v1.Endpoint` and the `EndpointInfo` interface. The `GetIdentity` function is also implemented by Cilium's `endpoint.Endpoint` struct (required for embedding).
The parser is modified use this newly available numeric security identity from the endpoint getter instead of relying on information from the `TraceNotify` struct.
This fixes a bug where the security identity was missing, because `TraceNotify` does not always contain the actual security identity (for example for `TRACE_FROM_LXC` events).
Fixes: #155
=>  parser: Use numeric security identity from endpoint

pkg/container/priority_queue.go, pkg/container/priority_queue_test.go, pkg/container/ring.go
This priority queue will be used for multi-node support in order to be able to re-order events in chronological order as they arrive.
Updates #89
=> container: add a priority queue implementation for events

cmd/serve/serve.go, pkg/server/local_observer.go, pkg/server/local_observer_test.go, pkg/server/observer.go, pkg/server/observer_test.go
When Hubble runs in embedded mode inside Cilium, the event queue size
must be big enough so the Hubble flow decoder can keep up with short
bursts of flows. The current calculation of 1% of the ring buffer size
has proven to be too small for embedded mode. For comparision, Cilium
monitor uses a event queue size of 1024 * NumberOfCPUs.
However, when Hubble runs as its own process reading from the Cilium
monitor socket, the Cilium monitor queue already acts as this buffer.
Therefore the Hubble event size is less critical. In fact, it was
capped at 100. This PR simplifies the logic and sets the default for
stand-alone mode to 128.
The value for embedded mode will be configurable in cilium-agent.
Ref: #161
=> server: Make event queue size configurable

cmd/root.go, cmd/version/version.go, pkg/version.go
This PR adds a `--version` flag to the root command:
```
$ hubble --version
hubble v0.0.0
```
As well as a `version` subcommand for more detailed version information:
```
$ hubble version
hubble v0.0.0 compiled with go1.14 on linux/amd64
```
This command is meant to provide more information in the future such as the commit hash, the server version/mode, etc.
=> add version information

cmd/serve/serve.go, pkg/server/local_observer.go
Move around log messages a bit so that the configuration parameters for
Hubble gets printed in both standalone and embedded mode. Info logs look
like this in standalone mode after the change:
level=info msg="Started server with duration" duration=0s
level=info msg="Configured metrics plugin" name=flow status=
level=info msg="Configured metrics plugin" name=dns status="query,"
level=info msg="Configured metrics plugin" name=drop status=
level=info msg="Configuring Hubble server" eventQueueSize=128 maxFlows=131071
level=info msg="Starting gRPC server on client-listener" client-listener="0.0.0.0:50051"
level=info msg="Starting gRPC server on client-listener" client-listener="unix:///var/run/hubble.sock"
=> server: Log server configuration parameters

Makefile, cmd/version/version.go, pkg/version.go
Example output:
$ hubble version
hubble v0.0.0@master-9299103 compiled with go1.14 on linux/amd64
This information is omitted when `git` is not available:
$ hubble version
hubble v0.0.0 compiled with go1.14 on linux/amd64
=> add git branch and hash information to version command

pkg/api/v1/endpoint.go, pkg/api/v1/endpoint_test.go, pkg/api/v1/types.go, pkg/cilium/endpoint.go, pkg/cilium/endpoint_test.go, pkg/parser/endpoint/endpoint.go, pkg/parser/endpoint/endpoint_test.go, pkg/testutils/fake.go
The endpoint cache contained a few artifacts from early versions of
Hubble where flows were decoded late, i.e. when a gRPC flow requested
them. This meant that the endpoint cache had to keep "historic" data
about endpoints around. This was done by tracking endpoints deletion
time using Endpoint's Deleted field.
As now now, however, endpoint information is annotated as soon as a flow
is observed, making it pointless to keep deleted endpoints around.
This commit removes the Deleted field from the Endpoint struct and
adjust the code so that when an endpoint has to be deleted, it is
actually deleted rather than soft-deleted then garbage collected.
This also removes the need to garbage collect soft-deleted endpoints
from the endpoint cache.
Ref: #76
=> api/endpoint: stop marking endpoints as deleted, just remove them

pkg/container/ring.go, pkg/container/ring_reader.go, pkg/container/ring_reader_test.go, pkg/container/ring_test.go
This is a first step towards fixing #82. This uses
`atomic.{Load,Store}Pointer` to access the individual slots in the ring
buffer, ensuring that each write is properly propagated to all other
threads. While it seems to satisfy the Go race detector, it seems that
running the unit test now with `-race` will now sometimes fail with a
semantic error, i.e. the ring buffer content is not what is expected.
This indicates that there remains a real race condition somewhere, this
commit only addresses the data race discovered by the Go race detector.
This means that #142 remains blocked, as we also have to find the root
cause for the race condition. Tests pass consistently when running
this commit without `-race` however, therefore it does not seem to
introduce any regressions.
Signed-off-by: …
=> container/ring: Fix various data races and race conditions

install/kubernetes/hubble/templates/daemonset.yaml, install/kubernetes/hubble/templates/deployment.yaml
Don't mark Hubble pod as system-node-critical if it's not in kube-system
namespace. Later versions of Kubernetes don't have this restriction, but
for now I'm simply setting this field based on which namespace Hubble is
in.
Ref: https://github.com/kubernetes/kubernetes/pull/76310
Ref: https://github.com/cilium/cilium/issues/10504
=> helm: Add priorityClassName for kube-system only

cmd/observe/observe.go, cmd/serve/serve.go, go.mod, pkg/printer/options.go, vendor/modules.txt
The `syscall` package is deprecated since Go 1.4:
> Deprecated: this package is locked down. Callers should use the
> corresponding package in the golang.org/x/sys repository instead. That
> is also where updates required by new systems or versions should be
> applied. See https://golang.org/s/go1.4-syscall for more information.
In effect the `syscall` package is not updated, "not even to keep pace with changes in operating systems it references".
This commit replaces references to the `syscall` package by `golang.org/x/sys/unix`, as hinted by the Go documentation of the `syscall` package. This has already been done on Cilium (see https://github.com/cilium/cilium/issues/10116).
=> cmd: remove syscall references

pkg/cilium/dns.go, pkg/cilium/dns_test.go, pkg/parser/seven/parser_test.go, pkg/parser/threefour/parser_test.go, pkg/testutils/fake.go
- Define GetNamesOf by composing getters.DNSGetter instead of redefining
the same method.
- Move FakeFQDNCache to testutils package.
- Remove FakeDNSGetter since FakeFQDNCache can act as a fake DNSGetter.
=> fqdn: Refactor FqdnCache interface

cmd/serve/serve.go, pkg/api/socket.go, pkg/api/socket_test.go
This commit allows to specify a group owner for configured unix domain sockets listeners. This is useful when Hubble is embedded into Cilium so that the Hubble socket group can be set to the default Cilium group rather than one specific to Hubble, which does not make sense in such context.
=> cmd: make SetupListeners public, allow specifying socket group

pkg/server/local_observer.go, pkg/server/local_observer_test.go, pkg/server/serveroption/option.go
This introduces hooks to allow libraries to extend the way Hubble
processes events and flows. An example of this could be the metrics
package, which is currently hard-coded into the decoding pipeline.
This commit introduces three initial hooks in the server:
1. `OnServerInit`: Invoked after all server options have been parsed.
This is mostly intended for hooks to obtain the finalized list of
server properties, for example to obtain a reference to the
Cilium daemon when running inside Cilium.
2. `OnMonitorEvent`: Invoked after an Cilium monitor event has been
observed, but not yet decoded.
3. `OnDecodedFlow`: Invoked after the parser has decoded the event,
provides write access to the fully populated `pb.Flow` before it
is added to the ring buffer.
Co-Authored-By: Glib Smaga …
=> server: Introduce hooks for extending server functionality

pkg/api/v1/endpoint.go, pkg/api/v1/endpoint_test.go
If the endpoint to compare with is `<nil>`, it leads to a runtime error due to a nil pointer dereference.
This commit addresses this issue by returning false when the given endpoint to compare with is <nil>.
Note that although this commit fixes the runtime panic as reported in #197, it doesn't address the root cause of the problem as endpoints in the endpoints cache are never supposed to be `<nil>`.
Fixes #197
=> api: fix potential panic in endpoint's EqualsByID

pkg/version.go
Not much can be done for 0.5.0 without force pushing the tag. I'll put together a releasing.md to make sure some things like correcting the version before tagging are checked off.
https://github.com/cilium/hubble/issues/201
=> Set version to 0.6.0-dev

cmd/serve/option.go, cmd/serve/serve.go, cmd/serve/server.go
When running in embedded mode, Hubble server will implement additional
gRPC services that do not exist in standalone mode (notably, the
in-development service for Hubble peers discovery that will be used by
the multi-node feature and will be a Hubble embedded only feature).
Parts of cmd/serve are already used by embedded Hubble. However, as the
code stood before this commit, customizing the Hubble server to add new
gRPC services for embedded mode without affecting standalone mode was
not possible.
This commit creates a new Server struct that can be configured using
options. For Hubble standalone, this commit brings no functional
changes. However, it will enable Hubble embedded to configure additional
gRPC services.
Ref: #89
=> cmd/serve: refactor, introduce Server struct and options

cmd/observe/observe.go
Using DurationVar allows to defer time duration parsing to the pflag module instead of doing it by-hand.
=> cmd/observe: use flags.DurationVar instead of StringVar for timeout flag

pkg/server/local_observer.go
Filters are potentially expensive, time ranges have a constant cost.
Match it first.
Signed-off-by: Thomas Graf <thomas@cilium.io>
=> server: Match time range before filters

.github/workflows/unittests.yml, Dockerfile
Note: currently blocked by https://github.com/docker-library/golang/issues/322.
=> update Go version to v1.14.2

cmd/observe/observe.go
Seems like most people don't care for it.
=> observe: Disable port-translation by default

cmd/observe/observe.go, cmd/status/status.go, pkg/defaults/defaults.go
This PR brings back the `HUBBLE_DEFAULT_SOCKET_PATH` environment variable to overwrite the default Hubble socket path. This environment variable key is the same as the one present in Hubble v0.5.
It was removed 24bc03b by accident. Overwriting the default Hubble socket path has proven to be useful for forward-compatibility. The mechanism for example is used to point the Hubble 0.5 client to the new socket path in cilium-embedded Hubble in CI.
=> Bring back HUBBLE_DEFAULT_SOCKET_PATH env var

cmd/observe/observe.go, cmd/observe/observe_filter_test.go
Filtering out certain event types by default on the client-side does
not make sense any more since the server already ignores events like
MessageType{Agent,Capture,Debug}. It can also be confusing when new
event types get added since they don't show up if you simply run
`hubble observe` without explicitly whitelisting the new event type.
=> observe: Show all the event types by default

install/kubernetes/hubble/values.yaml
*Reviewer note: This is PR targeting the `v0.5` branch.*
In the Cilium documentation, we ask users to obtain the Hubble v0.5
chart via the v0.5 branch. Therefore we should make sure that our chart
refers to v0.5 image tags.
Ref: https://github.com/cilium/cilium/pull/11121
=> helm: Pin Hubble v0.5.1 in v0.5 branch

cmd/root.go
They were buried quite deep in the file, put them right up
top with the root command.
=> cmd: Make all sub-commands more prominent

Documentation/dns_visibility.md, policies/l7_80_53.yaml, tutorials/deploy-hubble-and-grafana/example-apps/dns-visibility.yaml
There is a subtle difference between `- {}` and `- matchPattern: '*'`.
More specifically, the former matches the record name `.`, whereas the
latter doesn't. You can use `dig NS .` to test this behavior.
=> doc: Update DNS visibility policy

pkg/printer/printer.go, pkg/printer/printer_test.go
This commit makes the printer fall back on the MAC addresses from the
Ethernet header in case there is no IP payload.
Before:
May 25 13:20:58.770 [k8s2]:  ->  from-endpoint FORWARDED (Ethernet)
After:
May 25 13:20:58.770 [k8s2]: 16:62:96:09:81:a6 -> 8a:ed:ae:7c:9c:29 from-endpoint FORWARDED (Ethernet)
=> printer: Fall back on ethernet MAC addresses

Makefile
Use the `-s -w` linker flags when compiling hubble in order to reduce the binary size.
The `-w` linker flag omits DWARF symbol table whereas the `-s` flag omits the symbol table and debug information.
This reduces the binary size from 18M to 13M.
=> make: optimize binary size by omitting symbol table and debug info

Makefile, cmd/profile.go, cmd/root.go
Since the hubble binary is only used as a client, there is not much
value in providing pprof support by default. This commit hides the
pprof logic behind a go build tag.
This reduces the binary size by ~150KB.
=> cmd: Make pprof optional

.github/workflows/unittests.yml, Dockerfile, Makefile
This PR backports a minor bugfix and Go version bump to v0.5.
=> backport/v0.5: update Go version, pull in a fix

.github/workflows/unittests.yml, Dockerfile
This is a backport for the v0.5 branch.
=> update Go version to v1.14.4 and alpine base image to v3.12

RELEASE.md
Following a small doc should be a lot easier and less
error-prone than trying to do it from memory each time.
=> Add RELEASE.md with release checklist

.gitignore, Makefile, RELEASE.md, cmd/observe/observe.go, go.mod, pkg/version.go, vendor/modules.txt
See individual commits for details.
=> Generate release binaries

Makefile
Antediluvian versions of GNU make, such as the one shipped by default on
MacOS (GNU Make 3.81, the last GPLv2 version released back in 2006) do
not understand the `!=` operator which executes and assigns the results
to a variable. This results in the GIT_BRANCH and GIT_HASH variables not
being assigned on MacOS. This commit addresses this issue by using the
`$(shell ...)` construct instead.
=> make: fix git hash variable assignments for old make versions

Makefile
- Remove version from the artifact file names. This way we can reference
the latest release artifact without knowing the version, e.g.:
https://github.com/cilium/hubble/releases/latest/download/hubble-linux-amd64.tar.gz
- Remove the `release` directory at the beginning of `make release` to
make sure there are no dangling files from previous releases.
- Clean up the `release/$OS` at the end of `make release`. This way
the directory only contains artifacts that need to be uploaded.
Fixes #292
=> Remove version from release artifact file names

.github/workflows/unittests.yml, Makefile, RELEASE.md, contrib/scripts/release.sh
- Use make clean to delete the release directory.
- Run `make release` from inside a docker container to ensure that the
artifacts get generated in a reproducible environment.
- Generate release artifacts as a part of the build.
=> Build release artifacts inside a container

.github/workflows/unittests.yml, Makefile, RELEASE.md, contrib/scripts/release.sh
Rename the current `release` make target to `local-release`, and update
the `release` target to generate release artifacts from inside Docker.
=> Remove contrib/scripts/release.sh

Documentation/installation.md, install/kubernetes/README.md, tutorials/deploy-hubble-servicemap/README.md
This PR ensures that we do not refer to the Hubble `master` branch in our Hubble v0.5 docs, as in Hubble 0.6 and latest, those files (i.e. Helm charts and documentation) have moved to the Cilium repository and will soon be removed from the Hubble master branch.
In addition, the PR also replaces a few occurrences of the `v1.7.0` Cilium git tag with the `v1.7` Cilium git branch, which will pick up the latest Cilium 1.7 patch release.
=> v0.5: Pin Hubble and Cilium branches

cmd/observe/observe.go, pkg/printer/options.go, pkg/printer/printer.go, pkg/printer/printer_test.go
This output option serializes the entire GetFlowResponse using proto3's
JSON mapping so that the JSON format is consistent across all the event
types. The output looks like this:
```
% hubble observe --debug -o jsonpb 2>&1 | jq
{
"node_status": {
...
},
"node_name": "hubble-relay-565f76c75f-974d9",
"time": "2020-06-15T20:56:44.689246261Z"
}
{
"flow": {
...
},
"node_name": "hubble-relay-565f76c75f-974d9",
"time": "2020-06-15T20:56:44.689246262Z"
}
```
Here is the updated description of `--output` option:
```
-o, --output string      Specify the output format, one of:
compact:  Compact output
dict:     Each flow is shown as KEY:VALUE pair
json:     JSON encoding
jsonpb:   Output each GetFlowResponse according to proto3's JSON mapping
table:    Tab-aligned columns
```
Signed-off-by: Michi …
=> printer: Add jsonpb output

.gitattributes
This marks the go.sum and vendor/modules.txt file sas generated so that they are collapsed by default in Github pull requests.
=> .gitattributes: hide go.sum and vendor/modules.txt in pull requests

cmd/observe/observe.go, pkg/defaults/defaults.go
I couldn't tell from the help text what the intended default was here,
but there seems to be some special logic to try to ensure that the
number of flows is only restricted when no other selector parameters are
specified. Manually add the default string at the end so that we don't
have to restrict the number of flows to 20 by default when specifying
other selector criteria, but it's still apparent what the default
behaviour is.
=> observe: Document default flow count output

Makefile
Before this patch, `make release` would generate the release/ directory (and files underneath) owned by root:root. This is caused by the fact that the build happen as root inside the Docker container. As a result, a following `make clean` from outside the container as an unprivileged user would fail.
This patch fix the issue by chowning the release directory and files to the user uid and gid whom invoked make originally (i.e. from outside the container).
=> make: fix release build directory ownership

.github/workflows/unittests.yml, Dockerfile, Makefile
=> v0.6 backports 2020-07-22

README.md
The metrics are now documented in Cilium's main documentation website.
=> README: fix broken link to metrics documentation

cmd/status/status.go
This information is also provided by `cilium status` in Cilium 1.8 and newer.
```console
$ hubble status
Healthcheck (via unix:///var/run/cilium/hubble.sock): Ok
Max Flows: 4096
Current Flows: 4096 (100.00%) 
Flows/s: 9.20
```
Formatting is up for discussion. I opted to put it on a new line, but there are other variants, such as e.g. `Current Flows: 4096 (100%, 9.20 flows/s)`
Fixes #329
=> cmd/status: Add flows per second to `hubble status`

install/kubernetes/hubble/values.yaml
*This PR targets the `v0.5` branch.*
This bumps the Helm charts to use the latest v0.5 version. 
In the documentation, we refer to the v0.5 branch for people who want to install standalone Hubble. Users reading the Cilium 1.7 documentation will use these Helm charts to install Hubble.
=> helm: Bump image to v0.5.2

install/kubernetes/hubble/Chart.yaml, install/kubernetes/hubble/templates/clusterrole.yaml, install/kubernetes/hubble/templates/clusterrolebinding.yaml, install/kubernetes/hubble/templates/daemonset.yaml, install/kubernetes/hubble/templates/serviceaccount.yaml, install/kubernetes/hubble/templates/svc.yaml, install/kubernetes/hubble/values.yaml
_**NOTE**: This PR targets the v0.5 branch._
Allow users to enable the hubble-grpc Service (through `.Values.grpc.enabled`) without requiring Hubble UI to be enabled. Note that when Hubble UI is enabled, the hubble-grpc Service is enabled unconditionally since UI depends on it.
=> Allow enabling the hubble-grpc service without Hubble UI enabled

pkg/printer/printer.go
The package github.com/cilium/cilium/api/v1/observer is imported twice.
Consistently use the aliased observerpb import and drop the duplicate.
Found using staticcheck.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
=> printer: avoid duplicate import

.github/workflows/unittests.yml, Makefile, cmd/observe/observe.go, pkg/printer/printer.go
Add `staticcheck` to the `make check` target which will also run it as part of GitHub actions.
The first two commits fix remaining issues reported by `staticcheck`, the third commit enables the check. Currently, the following checks are disabled:
* SA1019 deprecation warnings: https://staticcheck.io/docs/checks#SA1019
* ST1000 missing package comment: https://staticcheck.io/docs/checks#ST1000
I guess the second one should eventually be fixed by adding package level godoc comments to all sub-packages.
=> Add staticcheck to `make check`

cmd/status/status.go
When max flows is zero, a division by zero occurs which causes `hubble
status` to report NaN. Don't report any flows ratio when max flows is
zero instead.
Fixes: #303
=> cmd/status: do not report flows ratio when max flows is zero

cmd/status/status.go
This is similar to the hubble status as reported by `cilium status` and
thus makes things a little more consistent and easy to read.
=> cmd/status: report current/max flows on the same line

pkg/printer/printer.go
As suggested in https://github.com/cilium/hubble/pull/344#discussion_r469441231
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
=> printer: use fmt.Fprintln instead of fmt.Fprintf

cmd/status/status.go
Backport #345 to v0.6 branch:
When max flows is zero, a division by zero occurs which causes `hubble status` to report NaN. Don't report any flows ratio when max flows is zero instead.
Fixes: #303
=> v0.6: cmd/status: do not report flows ratio when max flows is zero

tutorials/deploy-hubble-and-grafana/README.md, tutorials/deploy-hubble-servicemap/hubble-all-minikube.yaml
This PR updates the v0.5 branch in two places where we missed updating the Hubble version tag and a link that was still referring to Cilium v1.6.
=> v0.5: set hubble version to v0.5.2; fix Cilium ref link to v1.7

Dockerfile
Specifying ENTRYPOINT doesn't make sense for this image anymore since
it no longer runs Hubble server, and it's primarily used to access the
CLI. Remove ENTRYPOINT so that you can bash into the container without
providing additional arguments to override it.
=> Dockerfile: Remove ENTRYPOINT

install/kubernetes/README.md, install/kubernetes/hubble/values.yaml, tutorials/deploy-hubble-servicemap/hubble-all-minikube.yaml
The YAML files were still pointing to `latest`. For Hubble v0.5, Hubble UI v0.5 is required.
While there, also fix a bad reference to `grafana.json` file.
=> v0.5: fix Hubble UI tag to v0.5.0

cmd/observe/observe.go, pkg/printer/options.go, pkg/printer/printer.go, pkg/printer/printer_test.go
The node name gets ommited from the compact output by default since it takes up too much space. The node name can be displayed by adding the --node flag
Signed-off-by: Marco De Luca <marcodl404@gmail.com>
=> printer: ommit node name from output

cmd/peer/peer.go
While here, swap address <-> name to improve readability.
=> cmd/peer: print tls.ServerName when available

.gitignore, cmd/root.go
Honor platform specific user configuration directory to look for a
configuration file for hubble. In addition, look up in the current
directory first and fallback to `$HOME/.hubble`.
On Unix systems, the user specific configuration directory is
`$XDG_CONFIG_HOME` if non-empty, else `$HOME/.config`. On MacOS, it's
`$HOME/Library/Application Support` and on Windows it's `%AppData%`.
For example, on Linux the configuration file is now looked for in this
order:
1. `$PWD/config.yaml`
2. `$XDG_CONFIG_HOME/hubble/config.yaml`
3. `$HOME/.config/hubble/config.yaml`
4. `$HOME/.hubble/config.yaml`
Note that this is a breaking change as previously the configuration file
was expected to be found in `$HOME/.hubble.yaml`. As the latter is not
standard and not recommended, let's opt for the freedesktop …
=> cmd: honor user configuration directory for the configuration file

.github/workflows/unittests.yml
This check ensures that vendored deps are "clean".
=> actions: add go-mod check

cmd/root.go, cmd/status/status.go, pkg/defaults/defaults.go
Using symbol names such as defaults.DefaultDialTimeout or
defaults.DefaultRequestTimeout stutters (the word "default" is
repeated).  The package contents are always referred using the package
name as a prefix, so drop "Default" from these identifiers. Also see
https://blog.golang.org/package-names (section "Naming package
contents") and
https://github.com/golang/go/wiki/CodeReviewComments#package-names
Also unexport and rename DefaultSocketPathKey which is not used outside
pkg/defaults.
=> defaults: avoid stutter in exported names

cmd/config/config.go, cmd/config/get.go, cmd/config/reset.go, cmd/config/set.go, cmd/config/view.go, cmd/root.go, go.mod, vendor/modules.txt
```
$ hubble config -h
Modify or view hubble config
Usage:
hubble config [flags]
hubble config [command]
Available Commands:
get         Get an individual value in the hubble config file
reset       Reset all or an individual value in the hubble config file
set         Set an individual value in the hubble config file
view        Display merged configuration settings
...
```
=> Add config subcommand

RELEASE.md
This tool defaults to `cilium/cilium` as the base repository so one needs to pass `--repo cilium/hubble`.
Also, add a `v` in `--base v$LAST_RELEASE` as Github can't find the version to compare to otherwise.
=> release: fix `release` binary usage instruction

Dockerfile, Makefile
Current make release iterates over supported OS/Arch versions to
cross-compile release binaries. For all platforms that are NOT the same
as the one from which the build is run, CGO is automatically disabled.
This is expected as per [the reference documentation](https://golang.org/cmd/cgo/#hdr-Go_references_to_C):
> The cgo tool is enabled by default for native builds on systems where
> it is expected to work. It is disabled by default when
> cross-compiling.
However, when GOOS and GOARCH are the same as the host doing the build,
it seems that CGO is NOT automatically disabled. As we create release
binaries using an Alpine image, this means that the release binary for
Linux/AMD64 is dynamically linked against the musl libc. Example:
$ file hubble
hubble: ELF 64-bit LSB executable, x86-64, …
=> build: ensure that binaries are always statically built

Dockerfile, Makefile
This is a backport of #397 to the v0.7 branch.
=> v0.7: build: ensure that binaries are always statically built

Dockerfile, Makefile
- #355: Dockerfile: Remove ENTRYPOINT (@michi-covalent)
- #397: build: ensure that binaries are always statically built (@Rolinh)
=> v0.6: backport 2020-10-20

cmd/config/config.go, cmd/root.go
See commits for a longer explanation. This PR also updates the long help for the config command.
=> cmd: fix environment variable names for options with dashes

cmd/config/config.go, cmd/root.go
This is a backport of #407 for the v0.7 branch.
=> v0.7: cmd: fix environment variable names for options with dashes

Documentation/README.md, README.md, install/kubernetes/README.md
Rather than pointing users to the latest development documentation,
point them towards the current stable release so they're less likely to
hit random issues due to ongoing development.
=> docs: Point to stable documentation

cmd/config/get.go, cmd/config/reset.go, cmd/config/set.go
Add support for shell completion for keys for the `get`, `set` and
`reset` subcommands. This means that when using `<TAB>` after
`config get|set|reset`, the list of possible configuration keys is
offered for completion, improving the user experience.
Example with the `get` subcommand (using `zsh`):
```
$ hubble config get <TAB>
config                server                tls                   tls-ca-cert-files     tls-client-key-file
debug                 timeout               tls-allow-insecure    tls-client-cert-file  tls-server-name
```
=> cmd/config: add shell completion support for keys for get|set|reset

Makefile
This variable is used to set the tag for the docker image. It is now set to `latest` if the version string contains `-dev` and to the
`v${VERSION}` otherwise and was previously unassigned leading to always produce `latest` when building a docker image.
=> make: set missing IMAGE_TAG variable

Makefile
This is a backport of #432 to the v0.7 branch.
=> v0.7: make: set missing IMAGE_TAG variable

Makefile
This is a backport of #432 to the v0.6 branch.
=> v0.6: make: set missing IMAGE_TAG variable

go.mod, go.sum, vendor/gopkg.in/yaml.v2/.travis.yml, vendor/gopkg.in/yaml.v2/apic.go, vendor/gopkg.in/yaml.v2/go.mod, vendor/gopkg.in/yaml.v2/yaml.go, vendor/modules.txt
This version reverts the default line wrapping change introduced in v2.3.0, so we can remove our override in `go.mod`.
See https://github.com/go-yaml/yaml/commit/7649d4548cb53a614db133b2a8ac1f31859dda8c.
=> vendor: Bump gopkg.in/yaml.v2 to v2.4.0

cmd/completion/completion.go
Before this patch, the zsh completion was broken.
For zsh specifically, the first line of the completion file [must be a zsh autoload tag](http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Autoloaded-files):
>  Files whose first line does not start with one of these tags are not considered to be part of the completion system and will not be treated specially.
=> completion: remove the copyright header

pkg/printer/printer.go, pkg/printer/printer_test.go
Address two review comments for #442 which I forgot to push before merging:
https://github.com/cilium/hubble/pull/442#discussion_r540005414
https://github.com/cilium/hubble/pull/442#discussion_r539178607
=> Agent event follow-up fixes for #442

Makefile
Add support for `DOCKER_FLAGS` environment variable to the Makefile. This allows passing builder-specific flags to the docker build command, such as required when using Docker BuildX.
=> Makefile: Add support for DOCKER_FLAGS environment variable

cmd/observe/observe.go, cmd/observe/observe_filter.go, cmd/observe/observe_filter_test.go
Example Usage
**Note: the TCP flags values specified on the command line option are case-insensitive.**
```
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ ./hubble observe --tcp-flags SYN
TIMESTAMP             SOURCE                                      DESTINATION                                 TYPE                     VERDICT     SUMMARY
Dec 18 17:10:40.696   [fd00::b]:37948                             [fd00::c]:4240                              Stale or unroutable IP   DROPPED     TCP Flags: SYN
Dec 18 17:10:40.765   kube-system/coredns-76dcd4bd85-mwtf7:8181   10.11.0.241:42142                           from-endpoint            FORWARDED   TCP Flags: SYN, ACK
Dec 18 17:10:41.720   [fd00::b]:37948                             [fd00::c]:4240                              from-host …
```
=> cmd/observe: support for filtering events based on tcp-flags

cmd/observe/observe_filter.go, cmd/observe/observe_filter_test.go
The first commit add test coverage for the functionality changed in the successive commits.
The second commit does some small refactoring to avoid duplicating numeric sub-type parsing.
The third commit introduces the actual agent event sub-type filtering. One caveat was that the monitor API (`github.com/cilium/cilium/pkg/monitor/api`) doesn't provide the sub-type strings a form which would be convenient for CLI arguments (i.e. they contain spaces). Thus, `github.com/cilium/cilium/pkg/monitor/api.AgentNotifications` is duplicated in `cmd/observe` in more convenient form. A test is added to ensure the two maps are kept in sync.
See individual commit messages for more details.
=> cmd/observer: add support for agent event sub-type filters

cmd/node/list.go
The flag needs to be added to the command prior to registering the flag completion function.
=> cmd/node: fix completion of output flag

.github/workflows/codeql-analysis.yml
This adds CodeQL analysis to Hubble, similar to https://github.com/cilium/cilium/pull/14514.
=> ci: Add CodeQL analysis

.github/dependabot.yml
This adds Dependabot for Hubble, like https://github.com/cilium/cilium/pull/14694.
=> ci: Add dependabot configuration

.github/dependabot.yml
Before this patch, because the kind/enhancement label is prefixed by the `chart_with_upwards_trend` icon, dependabot would complain to be unable to find the "kind/enhancement" label. See for example https://github.com/cilium/hubble/pull/476#issuecomment-773892140
=> ci: fix dependabot kind/enhancement label

Makefile
Go 1.16 adds macOS ARM64 support so let's build release binaries for Apple silicon.
=> make: build release binaries for darwin/arm64 (aka Apple silicon)

cmd/common/conn/tls.go, go.mod, go.sum, main.go, pkg/printer/options.go
As of Go 1.16, the `io/ioutil` package has been deprecated. Corresponding functions have moved to the `os` and `io` packages.
This in turns means that Go 1.16 is now required to build Hubble.
=> all: avoid using the deprecated io/ioutil package

.github/workflows/release.yml, RELEASE.md
See commits for details. As release notes need to be manually edited, new releases are created as draft so that a maintainer can edit the release notes before publishing.
=> Automate release creation and artifacts publishing

.github/dependabot.yml
This reverts commit 0d7fbb978f880e9c345cd3966f3669aecbdaa778.
See https://github.com/cilium/hubble/pull/492#issuecomment-783141026, the attempted fix introduced by https://github.com/cilium/hubble/pull/477 did not work. Consequently, I'm proposing to remove the icon from the `kind/enhancement` label and reverting the buggy dependabot fix.
=> Revert "ci: fix dependabot kind/enhancement label"

CONTRIBUTING.md
While here, make the link point directly to the channel.
=> doc: #hubble-devel on Slack is now #sig-hubble

go.mod, go.sum, vendor/google.golang.org/grpc/encoding/proto/proto.go, vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go, vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go, vendor/google.golang.org/grpc/regenerate.sh, vendor/google.golang.org/grpc/rpc_util.go, vendor/google.golang.org/grpc/status/status.go, vendor/google.golang.org/grpc/version.go, vendor/modules.txt
=> vendor: bump google.golang.org/grpc to v1.36.0

cmd/peer/watch.go, cmd/peer/watch_test.go
This PR refactors a small piece of processing code and adds tests.
Signed-off-by: Simarpreet Singh <simar@linux.com>
=> cmd/peer: Refactor and test processing of response

go.mod, go.sum, vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go, vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go, vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go, vendor/github.com/google/go-cmp/cmp/report_compare.go, vendor/github.com/google/go-cmp/cmp/report_slices.go, vendor/modules.txt
=> vendor: bump github.com/google/go-cmp from 0.5.4 to 0.5.5

cmd/observe/observe.go, cmd/observe/observe_filter.go
When debugging, it can be really useful to know about the filters that have been generated.
Example:
$ hubble --debug observe --ip 9.9.9.9  > /dev/null
Using config file: /home/user/.config/hubble/config.yaml
Using filters:
=> include: [{"source_ip":["9.9.9.9"]},{"destination_ip":["9.9.9.9"]}]
=> exclude: <nil>
=> cmd/observe: print filters in debug mode

cmd/observe/observe.go
This hides the flags "json", "compact" and "dict" from the help output and prints the replacement flag to use instead. E.g. for "json":
$ hubble observe --json
Flag --json has been deprecated, use '--output json' instead
=> cmd/observe: mark deprecated output flags as deprecated

go.mod, go.sum, vendor/honnef.co/go/tools/lintcmd/version/version.go, vendor/honnef.co/go/tools/unused/typemap/identical.go, vendor/honnef.co/go/tools/unused/typemap/map.go, vendor/honnef.co/go/tools/unused/unused.go, vendor/modules.txt
=> vendor: bump honnef.co/go/tools from v0.1.2 to v0.1.3

cmd/observe/observe.go, pkg/printer/options.go, pkg/printer/printer.go, pkg/printer/printer_test.go, pkg/time/time.go
This PR adds a new option to the observe command (`--time-format`) to allow specifying a different time format for timestamps. The default is unchanged and remains `time.StampMilli`. The following formats are supported:
```
--time-format string   Specify the time format for printing. This option does not apply to the json and jsonpb output type. One of:
StampMilli:   Jan _2 15:04:05.000
RFC3339:      2006-01-02T15:04:05Z07:00
RFC3339Milli: 2006-01-02T15:04:05.999Z07:00
RFC3339Micro: 2006-01-02T15:04:05.999999Z07:00
RFC3339Nano:  2006-01-02T15:04:05.999999999Z07:00
RFC1123Z:     Mon, 02 Jan 2006 15:04:05 -0700
(default "StampMilli")
```
In addition, new formats are supported for the `--since` and `--until` flags, namely `RFC3339` and `RFC3339[milli|micro|nano]` and `RFC1123Z`.
=> cmd/observe: add a new flag to allow specifying different time formats for timestamps

RELEASE.md
Cherry-pick the release documentation update from PR #516 which targeted the v0.7 branch.
=> Update RELEASE.md with `-dev` change

cmd/observe/observe.go, cmd/observe/observe_test.go, cmd/root.go, go.mod, pkg/logger/logger.go, vendor/modules.txt
Following up on 63d154c, print the entire GetFlowsRequest instead of
only printing filters.
Here is a sample output:
% ./hubble observe --since 2021-03-02T01:09:31Z --last 1 -t drop --debug
Sending a request: {"number":"1","whitelist":[{"event_type":[{"type":1}]}],"since":"2021-03-02T01:09:31Z"}
=> cmd/observe: Print the entire request in debug mode

pkg/printer/printer.go, pkg/printer/printer_test.go
Keep the original source on the left and use "<-" for reply packets.
Before:
```
2021-04-22T03:51:42Z: 10.168.0.11:33192 -> kube-system/kube-dns-5d54b45645-p9kvw:8081 to-endpoint FORWARDED (TCP Flags: SYN)
2021-04-22T03:51:42Z: kube-system/kube-dns-5d54b45645-p9kvw:8081 -> 10.168.0.11:33192 to-stack FORWARDED (TCP Flags: SYN, ACK)
2021-04-22T03:51:42Z: 10.168.0.11:33192 -> kube-system/kube-dns-5d54b45645-p9kvw:8081 to-endpoint FORWARDED (TCP Flags: ACK)
2021-04-22T03:51:42Z: 10.168.0.11:33192 -> kube-system/kube-dns-5d54b45645-p9kvw:8081 to-endpoint FORWARDED (TCP Flags: ACK, PSH)
2021-04-22T03:51:42Z: kube-system/kube-dns-5d54b45645-p9kvw:8081 -> 10.168.0.11:33192 to-stack FORWARDED (TCP Flags: ACK, PSH)
2021-04-22T03:51:42Z: kube-system/kube-dns-5d54b45645-p9kvw:8081 -> …
```
=> compact: Always print original source on the left

cmd/observe/observe.go, cmd/observe/observe_test.go
As of commit 5071eca2f964 ("Bump github.com/cilium/cilium to pull in
reworked agent/debug event API"), the agent and debug event types are no
longer handled by the GetFlows API and the newly introduced recorder
capture has its own API as well, see commit df71f17a5be6 ("cmd: Add
record subcommand").
Thus, also the filtering on these in "hubble observe" which uses the
GetFlows API doesn't work. Omit these types from the --type/-t option.
Also add a test to ensure the list of supported event types are in sync
with the respective event types supported by the monitor API.
Before:
```
$ hubble observe -h
...
-t, --type filter             Filter by event types TYPE[:SUBTYPE] ([l7 agent policy-verdict recorder drop debug capture trace])
...
```
After:
```
$ hubble observe -h
...
-t, --type filter …
```
=> cmd/observe: don't list agent/debug events and recorder captures in event type filter

cmd/common/config/flags.go, pkg/defaults/defaults.go
The default server address was set to the UNIX domain socket of Hubble
server for historical reasons. This socket is only available when
running the Hubble CLI from within a Cilium container, which is not the
recommended way to use Hubble nowadays. Users are typically recommended
to port forward the Hubble Relay service port locally to access Hubble
via the CLI. As Hubble Relay is available since Cilium v1.8, it makes
sense to change the default to the address that is the most commonly
use.
For Hubble CLI to continue working as before when within the Cilium
container, the `HUBBLE_SERVER` environment variable should be set to the
UNIX domain socket address.
=> change default address to localhost:4245

cmd/observe/observe.go
Before this commit, the default output format was set to "compact" when
in follow mode and to "tab" otherwise. Automagically changing default
values based on flags can be off-putting for users. To address this, one
should use a default that is static. As the "tab" output is not
compatible with follow mode, the "compact" output seems like a
reasonable default that works with all flags.
=> RFC: cmd/observe: set default output format to "compact"

Dockerfile
In Alpine 3.11 and 3.13, 'nslookup' exits with the error code 1 if it
can't resolve all IPs for the search list defined in /etc/resolv.conf
However, it seems that Alpine 3.10 and 3.12 are not affected by this bug
and continue return the error code 0 if at least on of the domains in
the search list is resolved into an IP address. Thus, we will use the
latest Alpine image available for the 3.12 release series.
Signed-off-by: André Martins <andre@cilium.io>
=> Dockerfile: use alpine 3.12

cmd/list/list.go, cmd/list/node.go, cmd/list/node_test.go, cmd/root.go
We recently decided to try and uniformize the Hubble CLI subcommands and
agreed on a `[verb] [noun]` approach. Given that there hasn't been any
release of Hubble CLI with the `nodes` subcommand yet, change the
`hubble nodes list` command for `hubble list nodes`.
=> cmd: change "node list" command for "list node"

cmd/root.go, cmd/watch/peer.go, cmd/watch/peer_test.go, cmd/watch/watch.go
We recently decided to try and uniformize the Hubble CLI subcommands and
agreed on a `[verb] [noun]` approach. This is a breaking change as there
has been releases of the CLI with the `peers` subcommand. However, this
command is hidden and not mentioned anywhere in documentation as it is
only useful to developers. Therefore, this change shouldn't affect end
users.
=> cmd: change 'peers watch' command to 'watch peers'

cmd/completion/completion.go, cmd/observe/agent_events.go, cmd/observe/agent_events_test.go, cmd/observe/debug_events.go, cmd/observe/debug_events_test.go, cmd/observe/events.go, cmd/observe/observe.go, pkg/defaults/defaults.go, pkg/time/time.go
This PR adds the `hubble observe agent-events` and `hubble observe debug-events` sub-commands to retrieve agent and debug events, respectively. These use the new `GetAgentEvents`/`GetDebugEvents` API introduced in cilium/cilium#15715.
Flags such as `--since`, `--until`,  `--follow` or `--time-format` are available for the sub-commands as well. Flow-specific flags (e.g. `--from-*`, `--http-*` or `--ip-translation` are restricted to `hubble observe` and not available in the sub-commands. See `hubble observe -h`, `hubble observe agent-events -h` and `hubble observe debug-events -h`.
Examples:
```
$ hubble observe agent-events
TIMESTAMP             TYPE                          DETAILS
Apr 26 13:32:03.225   ENDPOINT_CREATED              id: 3478
Apr 26 13:32:14.281   IPCACHE_UPSERTED …
```
=> Add subcommands for agent and debug events

.github/workflows/release.yml
This prevents the github-action plugin repository owner from potentially
being able to tamper with data that is being uploaded.
Note that updates to the github action plugins is being handled by
dependabot.
Suggested-by: André Martins <andre@cilium.io>
Signed-off-by: Robin Hahling <robin.hahling@gw-computing.net>
=> release: pin skx/github-action-publish-binaries to a specific sha

.github/workflows/release.yml
=> v0.8: release: pin skx/github-action-publish-binaries to a specific sha

.github/workflows/codeql-analysis.yml, .github/workflows/tests.yml
When updating a pull request, workflows associated with the previous version continue to run. A way to prevent that and cancel outdated workflows is to use concurrency groups.
This commit handles workflows triggered by pull requests and pushes. We define each concurrency group such that they are unique to the pull request (via PR number) if triggered by event `pull_request` or to the commit (via SHA) if triggered by event `push`.
=> .github: Cancel outdated PR and push workflows

Makefile
This allows users to overwrite the GO environment variable while still
using CGO_ENABLED=false. This for example is useful when testing
pre-releases of the Go compiler.
=> Makefile: Introduce GO_BUILD variable

pkg/printer/printer_test.go
Depending on how `go test` is invoked, the auto-detection in the
`github.com/fatih/color` library will enable/disable color support. For
example when invoked as `go test .` in the `pkg/printer` directory,
color output will be enabled while for running `go test ./...` in the
root directory color support is disabled.
Avoid this flaky behavior by disabling color output in all printer
tests.
=> pkg/printer: disable color output in tests

.github/workflows/tests.yml
Instead of instantiating a separate job checking out its own copy of the
code, move the module vendoring check to the build job which already has
the code checked out.
=> .github/workflows: move Go module vendoring check to build checks

cmd/observe/agent_events_test.go, cmd/observe/observe_filter_test.go, cmd/observe/observe_test.go
* Make `Test_getRequest` resilient against test execution order changes:
The test currently assumes to be run to be run with empty `selectorOpts`
which might not be true depending on the order tests are executed. Reset
`selectorOpts` since and until files like in the other `Test_get*Request`
tests.
* Move `TestAgentEventSubTypeMap` to other tests related to agent events
Noticed while working on #543
=> Small test cleanups

cmd/observe/observe.go
Change the default behavior with regard to `--last` when in follow mode.
Previously, running `hubble --debug observe --follow` resulted in the
following:
$ hubble --debug observe --follow
time="2021-06-17T16:20:25+02:00" level=debug msg="Sending GetFlows request" request="number:20 follow:true"
The new behavior is changed for the following (notice that `number` is
not set, ie 0):
$ hubble --debug observe --follow
time="2021-06-17T16:21:02+02:00" level=debug msg="Sending GetFlows request" request="follow:true"
There are use-cases where a user is not interested in events that are
already in Hubble's ring buffer cache but only in new ones. A typical
example is when using hubble for testing, e.g. for the connectivity
test.
Note that this PR is a slight change of behavior as, when `--last` is …
=> cmd/observe: do not set `--last` to 20 by default in follow mode

cmd/observe/observe.go, cmd/observe/observe_filter.go, cmd/observe/observe_filter_test.go, cmd/observe/observe_test.go
Preparatory refactoring for #543, split into a separate PR to ease review.
See individual commit messages for details.
=> cmd/observe: rename flow-related functions, types and import aliases

.github/workflows/tests.yml
Before this patch, git diff was used to ensure that Go modules were properly vendored. While it could catch a failure to update a vendored module, it would not fail when a module was not vendored (untracked).
This patch use git status instead of git diff, effectively catching untracked vendored modules as well.
Signed-off-by: Alexandre Perrin <alex@kaworu.ch>
=> ci: fix the go vendoring check

CODEOWNERS
Reviewed #576 a little too late: https://github.com/cilium/hubble/pull/576#pullrequestreview-689709536
=> CODEOWNERS: assign GH actions to github-sec team

.github/workflows/tests.yml, .golangci.yml, Makefile
Checks for missing Go documentation used to be covered by the now defunct project `golint`. Revive is a replacement for golint that is used by `golangci-lint`. However, `golangci-lint` [disables checks for missing Go documentation by default](https://github.com/golangci/golangci-lint/issues/456). The only way to re-enable them is apparently to suppress golangci-lint's default rules, which is what this commit does. Rules that triggered false-positive on this codebase have been manually added. The list of default exclude rules can be found by running `golangci-lint run --help`.
=> ci: enable checks for missing Go documentation

.github/workflows/tests.yml, Dockerfile, Makefile
Note that the Alpine had been downgraded from 3.13 to 3.12 at some point
due to a bug with busybox's nslookup implementation. This commit bumps
it to 3.14 as it seems that the bug is fixed(*) and that Alpine based
versions of Go images are only provided with Alpine 3.13 and 3.14.
(*): With Alpine 3.11 and 3.13, busybox's nslookup would return with
exit code 1 when at least one of the IP address for the search list
defined in `/etc/resolve.conf` cannot be resolved. With Alpine 3.10 and
3.12, nslookup would return exit code 0 instead. It seems that Alpine
3.14 shares the same behavior as Alpine versions 3.10 and 3.12.
=> update Go to v1.16.6, alpine to 3.14

Dockerfile
Commit 32cdf60b8a7b795f579bb3317094bb1cfd63f0fb wrongly stated that the bug described in the note below is fixed in Alpine 3.14. It turns out that it is not.
=> docker: add note about bogus busybox's nslookup implementation

Makefile
In github's tarballed source code, the '.git' directory is removed, and so
git commands will fail.  This change allows compilation of hubble from
the tarballed source code.
https://github.com/cilium/hubble/issues/307
=> git commands in the Makefile return the empty string if they fail.

cmd/observe/flows.go, cmd/observe/observe.go
This patch completely removes the `--json`, `--compact` and `--dict` flags that have been deprecated since version v0.5.0 release 1.5 year ago. See [this discussion](https://github.com/cilium/hubble/issues/602#issuecomment-895176283) for additional context.
=> cmd/observe: remove depreacted formatting flags (json, compact, dict)

cmd/observe/observe.go
This is a v0.8 branch backport of #603.
=> v0.8: cmd/observe: remove depreacted formatting flags (json, compact, dict)

pkg/printer/printer.go
Commit 099da23a07b008fdc7d1524631b4968eeeef5011 broke the dict output by dropping the newline after the flow separator. This commit adds back the missing newline.
=> printer: fix dict outout newline

pkg/printer/printer.go
This is backport of #615 to the v0.8 branch.
=> v0.8: printer: fix dict outout newline

cmd/status/status.go, pkg/printer/printer.go, pkg/printer/printer_test.go
The existing behavior is maintained and translated to the "compact" format, which is the default. In addition, new output format are supported: dict, json and table. These formats are consistent with the formatting options of the `observe` command.
=> cmd/status: add support for multiple output formats

Makefile
Go 1.17 added support for `windows/arm64`. This means we can now create binaries for Windows on ARM64.
=> build release binaries for Windows ARM64

.github/workflows/tests.yml, Dockerfile, Makefile
While here, also bump the base Alpine image and golangci-lint.
=> update Go to v1.17.1

.golangci.yml
Specify go version to be used by `stylecheck` along with some cosmetic changes on the way.
See also https://github.com/cilium/hubble/pull/620
=> ci: bump Go to 1.17 for golangci-lint

cmd/observe/flows_test.go
protobuf-go deliberately introduces instability into their error message
strings to discourage users from matching on error strings [1]. This
breaks Test_getFlowsRequestWithInvalidRawFilters in unpredictable ways.
This was e.g. the case for https://github.com/cilium/hubble/pull/650
where the error message was updated. Due to the instability, he test
again broke on https://github.com/cilium/hubble/pull/653
[1] https://github.com/protocolbuffers/protobuf-go/blob/01b51b4f96e6f04345af6153c1b69345f8e075b9/internal/errors/errors.go#L26-L34
Make the test resilient against this behavior by matching only against
the Hubble-specific part of the error string.
Fixes: 18dbc6c51bf7 ("observe: Add --allowlist / --denylist flags")
Fixes: 771bb4ad3441 ("vendor: Bump github.com/cilium/cilium to …
=> cmd/observe: match only Hubble-specific part of error in Test_getFlowsRequestWithInvalidRawFilters

cmd/observe/flows_test.go
v0.9 backport of #655
[ upstream commit da3233666ae7dc965263498f0a954f828493a469 ]
protobuf-go deliberately introduces instability into their error message
strings to discourage users from matching on error strings [1]. This
breaks Test_getFlowsRequestWithInvalidRawFilters in unpredictable ways.
This was e.g. the case for https://github.com/cilium/hubble/pull/650
where the error message was updated. Due to the instability, he test
again broke on https://github.com/cilium/hubble/pull/653
[1] https://github.com/protocolbuffers/protobuf-go/blob/01b51b4f96e6f04345af6153c1b69345f8e075b9/internal/errors/errors.go#L26-L34
Make the test resilient against this behavior by matching only against
the Hubble-specific part of the error string.
Fixes: 18dbc6c51bf7 ("observe: Add --allowlist / --denylist …
=> [v0.9] cmd/observe: match only Hubble-specific part of error in Test_getFlowsRequestWithInvalidRawFilters

.github/dependabot.yml
To properly update Cilium, the replace directive in go.mod needs to be
updated as well, something dependabot can't do.
=> .github: let dependabot ignore Cilium dependency

cmd/config/set.go
`hubble config set ...` fails to save the configuration file if the
configuration directory doesn't already exist thus requiring the user to
create it beforehand. To address this issue, this commit ensures that
the configuration directory exists when `config set` is invoked by
creating it when necessary.
Closes: #677
=> cmd/config: ensure that the configuration directory exist

pkg/ipcache/ipcache.go, pkg/ipcache/ipcache_test.go
The metadata source field in ipcache is not necessarily set to "k8s" in
newer versions of Cilium. This patch updates the ipcache initialization
logic to accept pod information from any metadata source.
Ref: https://github.com/cilium/cilium/issues/15698
Ref: https://github.com/cilium/cilium/pull/15706
=> ipcache: Accept metadata from any source

pkg/printer/color.go, pkg/printer/printer.go, pkg/printer/printer_test.go
This commit changes the default compact mode output to always display
the Cilium security identity. This is very useful when debugging policy
related issues, as those often occur when an endpoint does not have the
expected security identity assigned to it.
Screenshot below. Note the magenta `(identity)` fields which are added by this PR.
There is no flag to disable those identities in compact mode. Users who rely on stable output are asked to use the `json` or `jsonpb` output.
=> printer: Display security identity in compact output

Dockerfile
Missed by https://github.com/cilium/hubble/pull/715, I don't understand how it can work with the mismatching version/sha :shrug:
=> Dockerfile: fix golang image name to v1.18.2

cmd/common/template/usage.go, cmd/common/template/usage_test.go, cmd/list/list.go, cmd/list/node.go, cmd/observe/agent_events.go, cmd/observe/debug_events.go, cmd/observe/flows.go, cmd/record/record.go, cmd/reflect/reflect.go, cmd/root.go, cmd/status/status.go, cmd/watch/watch.go
Removes the need to set the usage template per subcommand by registering
the commands which should be displayed in --help for each subcommand.
=> Refactor usage template to determine --help flags using a registration pattern

cmd/observe/flows.go, cmd/observe/flows_filter.go, cmd/observe/flows_filter_test.go, cmd/observe/identity.go
https://github.com/cilium/hubble/pull/717 introduced display of security identity in the (default) compact output, which is awesome. While trying to copy/paste identities from the Hubble CLI output to its `--identity` flag, I found that named reserved identities were not supported.
After this patch, we can write `hubble observe --identity world` instead of `hubble observe --label reserved:world`.
=> named reserved identites support for `--{,from-,to-}identity`

cmd/observe/flows.go
The way the service field in Hubble flows has been implemented so far is that it only works if the destination IP is the service ClusterIP. This makes the following lines from hubble observe --help misleading:
--from-service filter     Show all flows originating in the given service ([namespace/]<svc-name>). If namespace is not provided, 'default' is used
--service filter          Show all flows related to the given service ([namespace/]<svc-name>). If namespace is not provided, 'default' is used
--to-service filter       Show all flows terminating in the given service ([namespace/]<svc-name>). If namespace is not provided, 'default' is used
This patch changes the help message to address the inaccuracy described above.
Fixes: #713
Signed-off-by: Dominique Illi illi.dominique.v@gmail.com
=> improve cli help text for service filtering

cmd/observe/flows.go
update the cli docs for source/destination IP filter
Fixes: #458 
Signed-off-by: slayer321 <sachin.maurya7666@gmail.com>
=> docs: update the cli doc with cidr range source/destination ip filter

cmd/observe/flows.go
Document pod/service filter prefix behavior
Fixes: #501 
Signed-off-by: slayer321 <sachin.maurya7666@gmail.com>
=> docs: Document pod/service filter prefix behavior

pkg/printer/printer.go, pkg/printer/printer_test.go
The default output (compact) makes it hard for a user to tell the
different event types apart. In particular, it is hard for a user to
distinguish a trace event from a policy verdict one.
This commit modifies the output for policy verdict events in two ways.
First, instead of printing the drop reason (which is redundant as also
printed out with the dropped flow) the string 'policy-verdict' along
with the policy match type string for the event (L3-Only, L3-L4,
L4-Only, all, none), is displayed.
Additionally, flows that are forwarded or redirected are printed as
ALLOWED, those that are dropped or error as DENIED and the audit ones as
AUDITED.
Example output from #570:
```
$ cat sample.json | hubble observe --output compact
Jun 10 12:50:15.555: default/cronjob-1623329400-8mg2z:43006 …
```
=> cmd/observe: improve policy verdict output in compact mode

pkg/printer/printer.go, pkg/printer/printer_test.go
=> compact: Add traffic direction to policy verdict events

.github/workflows/tests.yml, Dockerfile, Makefile
This includes various security fixes, see
https://go.dev/doc/devel/release#go1.18.4 for details.
=> Update Go to 1.18.4

.github/workflows/tests.yml, Dockerfile, Makefile
This includes various security fixes, see
https://go.dev/doc/devel/release#go1.17.12 for details.
Also update to alpine 3.16 because 3.14 is EOL and there thus is no
golang:1.17.12-alpine3.14 image.
=> v0.9: Update Go to 1.17.12, alpine to 3.16

cmd/common/template/usage.go, cmd/common/template/usage_test.go, cmd/list/list.go, cmd/list/node.go, cmd/observe/agent_events.go, cmd/observe/debug_events.go, cmd/observe/flows.go, cmd/record/record.go, cmd/reflect/reflect.go, cmd/root.go, cmd/status/status.go, cmd/watch/watch.go
Avoids conflicts when different sub-commands have the same command name.
(Eg: hubble status vs hubble foobar status).
Since commands paths rely on having parent-commands, we must initialize
the map containing the flagsets after all sub-commands have been added.
This was something I discovered after trying to add new sub-commands that have the same name as other sub-sub-commands.
=> Use command path when registering flagsets

.golangci.yml, cmd/common/template/usage.go, cmd/observe/flows_filter.go, pkg/printer/printer.go, pkg/printer/printer_test.go
As suggested by Robin. See individual commits.
=> ci: add new linters

pkg/printer/printer.go
[ upstream commit d7910888d26abf817841a1904c5fc6e462f6861f ]
We should check for the "reserved:" prefix in the label string, not vice
versa.
Found by the gocritic linter.
=> v0.10: printer: fix argument order in strings.HasPrefix call

cmd/observe/agent_events.go, cmd/observe/agent_events_test.go, cmd/observe/debug_events.go, cmd/observe/debug_events_test.go, cmd/observe/flows.go, cmd/observe/flows_test.go
At the moment, `hubble observe` command ignores `--until` flag if `--since` is not specified. It would be expected `--since` flag to not be a hard requirement for `--until` flag to be used on its own.
This patch makes `--until` flag to be consider without  having  `--since` flag as a prerequisite.
Fixes https://github.com/cilium/hubble/issues/519
Signed-off-by: ChrsMark <chrismarkou92@gmail.com>
=> Fix observe command not supporting --until without --since

cmd/observe/identity.go
Now that we vendor a version of Cilium including https://github.com/cilium/cilium/pull/20048 `identity.GetAllReservedIdentities()` consistently returned a sorted list already.
=> cmd/observe: stop sorting reserved identity names

.github/workflows/tests.yml, .golangci.yml, Dockerfile, Makefile, cmd/observe/io_reader_observer.go
=> Update Go to 1.19.3, golangci-lint to 1.50.1

.golangci.yml, cmd/observe/flows.go, cmd/record/record.go
See commits for details.
Ref: #812
=> ci: update golangci-lint config, add new linters

Makefile
The release build should run with the same numeric user and group id as the caller of the Makefile. This solves two problems:
1. The generated artefacts should be owned by the user who invoked the Makefile
2. `go build -buildvcs=true` (the default since Go 1.18) invokes git, and git requires that the .git folder is owned by the user invoking it.
Previously, we achieved this by creating a new user and group inside the container with the wanted uid/gid. The problem with that approach is it fails if the uid/gid is already taken (such as e.g. gid 123, which seems to be used by the GitHub runner as of recently). Therefore, instead of trying to create a new user, this commit now uses `setpriv` from util-linux to force the `make` process (and all its children) to run as the RELEASE_{UID/GID}. …
=> Makefile: Fix potential uid/gid collision by using setpriv

cmd/observe/events.go, cmd/observe/flows.go, cmd/status/status.go, pkg/printer/options.go, pkg/printer/printer.go, pkg/printer/printer_test.go
This commit removes the old deprecated JSON output and fully replaces it with the newer JSONPB output (based on proto3's json mapping).
This is a breaking change, users of `-o json` will have to adopt the output parsing slightly: Each emitted object is now wrapped in a `GetFlowsResponse`, which means that the flow object (the root of the previous JSON output) is now accessible via the `.flow` attribute. 
For example, a query of the form `hubble observe -o json | jq .source.labels` now needs to be written as `hubble observe -o json | jq .flow.source.labels`.
=> cmd: Make `-o json` an alias for `-o jsobpb`

.github/workflows/tests.yml, Makefile
> go1.19.5 (released 2023-01-10) includes fixes to the compiler, the
> linker, and the crypto/x509, net/http, sync/atomic, and syscall
> packages. See the Go 1.19.5 milestone on our issue tracker for
> details.
Release milestone:
https://github.com/golang/go/issues?q=milestone%3AGo1.19.5+label%3ACherryPickApproved
=> update Go to v1.19.5

.github/dependabot.yml
With only one PR per week it's possible that dependabot would never catch up updates. See also https://github.com/cilium/hubble/pull/836#pullrequestreview-1242647431 for context.
=> dependabot: increase pull request limit and interval

CHANGELOG.md
As discussed at https://github.com/cilium/hubble/pull/846#discussion_r1067065517
=> CHANGELOG: add links for each released version

.github/dependabot.yml, RELEASE.md
Hubble CLI currently maintains support for the last stable branch. To ensure security-relevant depencencies are updated, this commit introduces dependabot for the current (v0.11) stable branch with the following configuration:
- gomod dependencies are only updated if there is a security vulnerability in one of our dependencies.
- docker dependencies (i.e. the alpine base image)  are only updated to the next patch version
- github actions are always updated (this mirrors cilium/cilium's configuration)
The goal of this configuration is to ensure we pull in security relevant updates, while keeping the moving parts as low as possible in the stable branch.
=> github: Enable dependabot for stable branch

cmd/observe/agent_events.go, cmd/observe/debug_events.go, cmd/observe/flows.go, cmd/observe/flows_filter_test.go, cmd/observe/observe.go
Hubble observe is now an alias for `hubble observe flows`. The only major difference is the help text for `hubble observe` is now briefer and indicates it is an alias for `hubble observe flows`. Additionally, while refactoring, I removed the flow formatting flags from the general formatting flagset and just moved it to it's own flagset.
Fixes #543
=> Add hubble observe flows

cmd/common/config/compat.go, cmd/observe/events.go, cmd/observe/flows.go, pkg/printer/options.go, pkg/printer/printer.go
This commit introduces a new environment variable, `HUBBLE_COMPAT`, which can be used to restore old behavior in the presence of breaking changes. It's inspired by Golang's GODEBUG variable documented here: https://pkg.go.dev/runtime
The intent of this flag is to allow us introduce breaking changes in the CLI, while still preserving backwards-compatibility with older versions where needed. As an example, this commit also bring back the legacy `-o json` flow schema if `HUBBLE_COMPAT` is set to `legacy-json-output`. This allows older Cilium stable versions to pull in a newer version of the Hubble CLI as part of security updates, while preserving the behavior of the Hubble CLI that originally shipped with that Cilium version.
HUBBLE_COMPAT options are _not_ intended to be supported …
=> cmd: Introduce `HUBBLE_COMPAT=legacy-json-output`

cmd/common/config/compat.go, cmd/observe/events.go, cmd/observe/flows.go, pkg/printer/options.go, pkg/printer/printer.go
[ upstream commit 221b8eade18c4de431281ad11eab150fc527918d ]
This commit introduces a new environment variable, `HUBBLE_COMPAT`, which can be used to restore old behavior in the presence of breaking changes. It's inspired by Golang's GODEBUG variable documented here: https://pkg.go.dev/runtime
The intent of this flag is to allow us introduce breaking changes in the CLI, while still preserving backwards-compatibility with older versions where needed. As an example, this commit also bring back the legacy `-o json` flow schema if `HUBBLE_COMPAT` is set to `legacy-json-output`. This allows older Cilium stable versions to pull in a newer version of the Hubble CLI as part of security updates, while preserving the behavior of the Hubble CLI that originally shipped with that Cilium version. …
=> [v0.11] cmd: Introduce `HUBBLE_COMPAT=legacy-json-output`

cmd/cli_test.go, cmd/observe/agent_events.go, cmd/observe/debug_events.go, cmd/observe/events.go, cmd/observe/flows.go, cmd/observe/flows_filter_test.go, cmd/observe/io_reader_observer.go, cmd/observe/io_reader_observer_test.go, cmd/observe_help.txt, cmd/status/status.go
Add unit tests that just test the flag/command handling.
This should help prevent what happened in https://github.com/cilium/hubble/pull/851#issuecomment-1402002694.
=> Add unit tests for testing hubble args/flags handling

.github/dependabot.yml, RELEASE.md
I got confused by https://github.com/cilium/hubble/pull/877 and https://github.com/cilium/hubble/pull/878 having the same name until I saw that they were targeting different branches.
=> dependabot: prefix backport PRs with target-branch version

.github/cilium-values.yaml, .github/kind-config.yaml, .github/workflows/integration-tests.yaml, .github/workflows/tests.yml
I noticed we don't have any tests that actually hit cilium, so this should fix that.
=> .github: Add integration tests that installs cilium and queries it using Hubble CLI

Makefile
The `command -v` command is more portable than `which`, see standard link below:
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html
=> make: use `command -v` instead of `which` for better portability

cmd/cli_test.go, cmd/observe/agent_events.go, cmd/observe/debug_events.go, cmd/observe/flows.go, cmd/observe/flows_filter_test.go, cmd/observe/observe.go, cmd/observe_help.txt
Attempt number two for https://github.com/cilium/hubble/pull/851 and https://github.com/cilium/hubble/issues/543. 
Hubble observe is now an alias for hubble observe flows. The only major difference is the help text for hubble observe is now briefer and indicates it is an alias for hubble observe flows. Additionally, while refactoring, I removed the flow formatting flags from the general formatting flagset and just moved it to it's own flagset.
This is currently based on #874 which adds unit tests to ensure things do not break this time.
=> Hubble observe flows

cmd/observe/observe.go, cmd/observe_help.txt
Fixes #861 
Adds additional tip for the below flag
```
--last uint      Get last N flows stored in Hubble's buffer (default 20). When querying against Hubble Relay, this gets N flows per instance of Hubble connected to that Relay
```
=> Improve help message for --last option

cmd/observe/observe.go, cmd/observe_help.txt
The help message for the `--since` and `--until` flags of the `observe` command was misleading. To provide an example of each supported time format, Go time's layout format was used. However, the layout doesn't correspond to an actually valid time when the time zone is used. This is because to instruct Go's time formatting to use Z for the UTC timezone and a `±hh:mm` offset format otherwise (following the ISO8601 behavior), both `Z07:00` needs to be provided which, in itself, is an invalid timezone indicator as it means UTC (offset 00:00) and an offset of -07:00. To address this problem and improve the help output, this patch replaces `Z` in the formatting string by `-` so that the example formats print with the help are actually valid examples. Note that the help message for …
=> cmd/observe: improve help message for date formats of --since/--until

cmd/common/config/flags.go, cmd/observe/flows.go, cmd/observe/observe.go, cmd/observe_help.txt
Closes #942 
Motivation as described in the GH issue. Basically, automatically detecting stdin is fraught with gotchas and can cause issues when trying to use hubble CLI in GitHub actions. Instead, add a flag to explicitly support reading flows from a file or stdin.
=> Replace stdin detection with --flows-file flag which supports reading flows from a file or stdin

.github/workflows/build-images-release.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/integration-tests.yaml, .github/workflows/release.yml, .github/workflows/tests.yml
See also this blog post about GHA sunsetting Ubuntu 18.04: https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
=> ci: run codeql job on Ubuntu 22.04 and only on supported release branch

cmd/observe/flows.go
We only log when we make a request, not when we connect. I think logging connections separately from requests could be useful for debugging.
=> Log when connection is successful

cmd/observe/io_reader_observer.go, cmd/observe/io_reader_observer_test.go
Before this patch, when parsing JSON flows and encountering an unknown field, the CLI would log a warning and skip the flow.
Unknown fields is not uncommon however, e.g. when using the Hubble CLI against a more recent Hubble server version.
This patch
* emit the flow if successfully parsed while ignoring unknown fields,
* improve the warning message by hinting at upgrading the Hubble CLI,
* make it so the warning message is logged only once.
=> observe: warn on unknown field while JSON decoding

cmd/common/conn/tls.go
When a server requests a client certificate, it's not always required, so do not fail if a client certificate was not configured, instead let the server reject the request instead, in case it supports other authentication methods.
=> Do not fail if unable to provide client certificate when requested

.golangci.yml, cmd/common/config/flags.go, cmd/common/conn/auth.go, cmd/common/validate/auth.go, cmd/observe_help.txt, cmd/root.go
Use case: I want to configure my ingress controller to expose hubble relay with basic auth, but Hubble CLI cannot pass basic auth credentials through.
=> Add support for supplying basic authentication credentials

.github/workflows/build-images-release.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/integration-tests.yaml, .github/workflows/release.yml, .github/workflows/tests.yml
This is necessary for some actions to work, such as setup-helm, which only builds `lib/index.js` for releases, but in other cases, we probably should be using the tagged releases anyways. 
This will also need to be back ported to v0.11.
=> .github: Configure renovate tag comment on GHA images

.github/workflows/build-images-release.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/release.yml, .github/workflows/tests.yml
Backport of https://github.com/cilium/hubble/pull/1024 to v0.11
=> [v0.11] .github: Configure renovate tag comment on GHA images

.github/workflows/build-images-release.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/release.yml, .github/workflows/tests.yml, Makefile
Backport of https://github.com/cilium/hubble/pull/1029 to v0.11 branch.
=> [v0.11] Fix Renovate datasources

RELEASE.md
This is a follow up from https://github.com/cilium/hubble/pull/1011. Now that renovate.json5 is in the repo, we can easily link to it in our release.md for examples to help guide a developer making a release.
=> Add example links to renovate configuration in RELEASE.md

.github/workflows/build-images-release.yaml
Resolve #1048 
Update `.github/workflows/build-images-release.yaml` and shell scripts to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the file that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' -o -name '*.sh'  | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
run: |
echo ::set-output name=tag::${GITHUB_REF##*/}
```
**TO-BE**
```yml
run: |
echo "tag=${GITHUB_REF##*/}%22%20%3E%3E%20$GITHUB_OUTPUT
```
=> .github: Replace deprecated command with environment file

.golangci.yml, cmd/cli_test.go
While here, cleanup the golangci-lint config.
=> ci: enable new linters

Makefile
v0.11 backport of https://github.com/cilium/hubble/pull/1070
=> make: add renovate anchor to the release target golang image

Dockerfile, Makefile
Don't know why it's not picked up by Renovate bot :thinking: cc @chancez
=> build: Bump golang image to alpine v3.18

cmd/list/list.go, cmd/list/namespace_test.go, cmd/list/namespaces.go, cmd/list/node.go, cmd/list/node_test.go
Now that the Hubble Observer API supports GetNamespaces, implement it in Hubble CLI.
Relates to
- https://github.com/cilium/cilium/issues/25266 
- https://github.com/cilium/cilium/pull/25563
=> Add hubble list namespaces command

cmd/observe/flows.go, cmd/observe/flows_test.go, cmd/observe/observe.go, cmd/observe_help.txt, pkg/defaults/defaults.go, pkg/printer/printer_test.go
Follow-up to change in cilium exposing a new experimental field in `GetFlowsRequest`s: https://github.com/cilium/cilium/pull/23198
Usage example with custom field mask and JSON output format:
```
% hubble observe --experimental-field-mask time,verdict --output jsonpb
```
Usage example with default field mask and default output format:
```
% hubble observe --experimental-use-default-field-masks
```
Example of providing invalid fieldmask:
```
% hubble observe --experimental-field-mask time,verdict,invalid --output jsonpb
failed to construct field mask: proto: invalid path "invalid" for message "flow.Flow"
```
Example of providing custom field mask for non-JSON output format:
```
% hubble observe --experimental-field-mask time,verdict
compact output format is not compatible with custom field …
```
=> Add experimental-field-mask flags

cmd/observe/flows_filter.go, cmd/observe/flows_filter_test.go
=> fix workload and identity filters

go.mod, go.sum, vendor/github.com/cilium/cilium/AUTHORS, vendor/github.com/cilium/cilium/api/v1/models/ip_v4_big_tcp.go, vendor/github.com/cilium/cilium/api/v1/models/ip_v6_big_tcp.go, vendor/github.com/cilium/cilium/api/v1/models/kube_proxy_replacement.go, vendor/github.com/cilium/cilium/pkg/defaults/defaults.go, vendor/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/register.go, vendor/github.com/cilium/cilium/pkg/logging/logfields/logfields.go, vendor/github.com/cilium/cilium/pkg/option/config.go, vendor/github.com/go-openapi/errors/api.go, vendor/github.com/go-openapi/swag/util.go, vendor/github.com/vishvananda/netlink/handle_unspecified.go, vendor/github.com/vishvananda/netlink/link.go, vendor/github.com/vishvananda/netlink/link_linux.go, vendor/github.com/vishvananda/netlink/netlink_unspecified.go, vendor/github.com/vishvananda/netlink/route_linux.go, vendor/modules.txt
Note: version v1.14.0-rc.0 is dual tagged as v1.14.0-snapshot.5 to avoid issues with -snapshot being semantically higher than -rc.
=> vendor: bump Cilium to v1.14.0-rc.0

.github/workflows/build-images-release.yaml
The set-output command is deprecated. See this blog post for more information:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> ci: replace deprecated use of set-output

cmd/common/conn/tls.go
Only set GetClientCertificate if client certificate is configured.
In docs for `GetClientCertificate` it specifies:
>  GetClientCertificate must return a non-nil Certificate. If
>  Certificate.Certificate is empty then no certificate will be sent to the
>  server.
If a nil certificate is sent when the server requests a client
certificate, the client will return an error. Instead, only configure
GetClientCertificate if certificates are provided and the server may
choose to how to handle the lack of a client certificate.
This is needed primarily for when the server is using RequestClientCert,
which requests a certificate, but does not require the client to send
one.
Previously, you would see this log message:
```
transport: authentication handshake failed: mTLS client certificate requested, …
```
=> Fix client certificate requests when no client certificate is specified

cmd/observe/flows.go, cmd/observe/flows_test.go
Don't set --last to 20 if --input-file flag is specified to preserve the previous default behavior of processing all the flows from stdin.
=> Don't set --last if --input-file is specified

.github/renovate.json5
Recently, this package is maintained by cilium fork, so we don't want the bot to update.
=> renovate: Add client-go to disabled list

.github/workflows/tests.yml
Slowg is a new analyzer that is part of Cilium's linters. It checks for inappropriate use of `Logger.With` from the `log/slog` package.
Check the URL below for more:
https://github.com/cilium/linters#slowg
=> ci: run slowg analyzer

Documentation/README.md
The documentation has long been moved to cilium.io.
=> doc: update doc readme and remove broken links

cmd/cli_test.go, cmd/observe/flows.go
The raw-filter flags are broken since we bind them to viper twice with the same name, during initalization. Once for `hubble observe` and once for `hubble observe flows`. This means that only the flags for `hubble observe flows` work, as it is registered later and overwrites the binding for `hubble observe`
We fix this by only binding the flags of the command we actually run.
Fixes: #1201
=> Fix raw-filter flags by binding flags to viper only if command is run

cmd/observe/flows.go
The Hubble CLI provides multiple different flags to filter the returned
flows. However how these filters are combined is not entirely obvious.
This commit adds more detailed help message and multiple examples that
explain how these filters interact if more than one filter flag is
provided.
I struggled to make this concise and understandable, so I added more detailed examples. I'm happy about any input to improve this and make it clearer.
=> Add filter flag documentation and examples to help message

cmd/watch/peer.go
Before this patch, `hubble watch peers --help` would not show the server related flags (e.g. --server).
I took a quick look and both `list nodes` and `list namespaces` have the server flags setup, so `watch peers` is the only sub-command to miss them.
=> doc: add server flag documentation to watch peers

.github/workflows/integration-tests.yaml, .github/workflows/tests.yml, Dockerfile, Makefile
This reverts commit 404830083679765242dbf88a25bdf38c87b172ce. See https://github.com/cilium/hubble/pull/1244
=> Revert "chore(deps): update golang to v1.21.1"

.github/renovate.json5
`matchUpdateTypes` is the wrong option for limiting updates in the stable branch. When I wrote this config, it was based off Cilium's config, which I looked at, and has since changed to using `allowedVersions`. It seems we're all slowly learning the lesson of how to correctly configure renovate. Ref https://github.com/cilium/hubble/pull/1239#issuecomment-1750266739
=> renovate: Use allowedVersions to limit updates to stable branches

pkg/printer/printer.go, pkg/printer/printer_test.go
This change switches from reporting the calculate `Flows Per Second` field to the more up-to-date `flowsRate` field provided by the server.
If the server doesn't provide the flows rate, we fall back to calculating the flows per second using uptime and seen flows.
closes: #952
=> Display server provided flows rate

Makefile
In order to better support rebuilding Hubble CLI in downstream projects, it would be useful to be able to override some of the variables defined in the `Makefile`. We already support this in cilium/cilium, so I adapted that pattern for Hubble CLI.
=> Makefile: Support overriding build options via Makefile.override

cmd/common/config/flags.go, cmd/common/conn/conn.go, cmd/common/conn/tls.go, cmd/list/namespaces.go, cmd/list/node.go, cmd/observe_help.txt, cmd/status/status.go, go.mod, go.sum, vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/COPYRIGHT, vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/LICENSE, vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/timeout/doc.go, vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/timeout/timeout.go, vendor/modules.txt
Add the ability to configure the request timeout for unary RPCs (ServerStatus, ListNodes, ListNamespaces). Previously this was hardcoded at 12s and could not be overridden. I didn't implement this for streaming RPCs because timeouts for streams is significantly more nuanced.
Also updates a few cases where we're creating a cancellable context to cancel after the command func runs, but cobra provides a context for exactly that already, so use it.
=> Add request timeout flag for unary RPCs

cmd/observe/flows_filter.go, cmd/observe/flows_filter_test.go
This PR essentially implements @kaworu's proposal in https://github.com/cilium/hubble/issues/359#issuecomment-702202613 .
This means instead of treating the `--namespace` flag as an alias for filtering for any pod in the namespace, we now treat the `--namespace` flag as a modifier for the `--pod` and `--service` flag. We also  try to catch namespace inconsistencies in flags and fail early.
There where a few edgecases that were not considered in the initial proposal:
* If we provide multiple namespace and/or pods/services we build the crossproduct of the provided values.
For example `hubble observe -n foo -n bar --pod buzz` will return any flows from or to pods in namespace `foo` or `bar` named `buzz`
* If we don't provide any pod or service flags, i.e. `hubble observe -n foo`, we use the …
=> Make `--namespace` flag more intuitive and allow both `--namespace` and `--pod` flag

cmd/observe/flows.go, cmd/observe/flows_filter.go, cmd/observe/flows_filter_test.go, cmd/observe_help.txt
This is just a short-cut to `--node-name <cluster-name>/` but should make it more easier for users to filter by cluster, since many users are not aware the cluster name is part of the node name field on a flow.
=> Add --cluster flag for filtering by cluster

cmd/observe/flows.go, cmd/observe/flows_filter.go, cmd/observe/flows_filter_test.go, cmd/observe_help.txt
This PR introduces `to-all-namespaces`, `from-all-namespaces`, and `all-namespaces` flags that allow filtering for services and pods in all namespaces.
This allows us to for example list any flows to a service named `bar` in any namespace using
```
hubble observe --all-namespaces --service bar
```
This PR builds on https://github.com/cilium/cilium/pull/28921
Closes: #359
=> Add flags to filter for pods and services in any namespace

.github/renovate.json5
This should hopefully reduce the noise a bit and concentrate the updates during one part of the day weekly.
=> Adjust renovate limits

.github/workflows/codeql-analysis.yml, .github/workflows/integration-tests.yaml, .github/workflows/tests.yml, Makefile, go.mod
Also use go.mod for version for setup-go GHA. Adapted from https://github.com/cilium/hubble/pull/1397 in main, I wanted to update Go (without waiting for renovate) and noticed we had the version spread out in so I also updated to source the version from `go.mod` when possible.
=> [v0.13] Update Go to 1.21.8

.github/renovate.json5
These were never updated to reflect the new base image versions in 0.13
=> .github: Update renovate for v0.13 branches

.github/workflows/build-images-release.yaml
This commit changes the "build-image-release.yaml" such that runs for every pull request and commit to the `main` branch. This ensures the build is tested before the actual release.
The credentials to push to quay.io are only available in the `release` deployment environment. This commit therefore changes the workflow to only use that environment if the workflow was triggered for a `v*` git tag. The `release` environment also needs approval from a Hubble maintainer, so the risk of accidentally pushing a release from a development branch is rather low.
=> github: Run Docker build on all PRs

Makefile
Adds a target to the Makefile to help with running and debugging renovate locally. I've been using this in a few other repos and it's pretty helpful. Note that it's not aware of anything other than the current checkout, so if you want to test it against other branches, you will have to change branches (meaning the Makefile target may not exist), and/or adjust the rules in the `renovate.json` as needed for testing.
=> Makefile: Add renovate-local target

README.md
=> README: Fix CLI example

.github/workflows/build-images-release.yaml
Use the same tag regex as the `Create a release` workflow [^1]. No need to be extra fancy since this workflow is protected by an environment that requires an approval from a maintainer.
[^1]: https://github.com/cilium/hubble/blob/6274cee68c7abd28619f88c2d17dcb4b178a2e7e/.github/workflows/release.yml#L5
=> build-images-release: Simplify the tag regex

.github/workflows/build-images-release.yaml
This commit introduces a fix for the "Display Digests" job of the image build workflow. The job fails when trying to download image digest artifacts, which is caused by a recent change made to the docker/build-push-action that adjusted the way artifacts were stored. The fix is based off of
https://github.com/cilium/cilium/pull/33216, more details can be found there.
=> build-images-release: Specify pattern when downloading image digests

Makefile
2 commits:
- drop building 32-bit release binaries
- use hubble target to build release binaries
=> Makefile cleanups / improvements

CODEOWNERS
Now the only dependency is github.com/cilium/cilium [^1]. Let's not pull in the vendor team for reviewing that.
[^1]: https://github.com/cilium/hubble/blob/5fcb8c343b65fb894c820b7558387d69cbdde446/go.mod#L5
=> Remove the vendor team from CODEOWNERS

.github/ISSUE_TEMPLATE/release.md
Use GitHub Slack app to post a message in the #release channel instead [^1].
[^1]: https://cilium.slack.com/archives/C011Y14D0G0/p1732210525349309
=> release: Remove the step to post a Slack message

.github/renovate.json5
Commit 5ef17d1368802fef26765e111136f8bd06474da3 missed a conversion from `matchFiles` to `matchFileNames`.
=> migrate Renovate config take #2
